### ISSUE TITLE
Timeout in the "Settings" Tab

### ISSUE THREAD

**Issue by pwe123345** [MrMEEE/awx-build#102]
Hello,

after a newly installation I tried to configure LDAP Authentication according to my previous working setup.
I was confronted with several "HTTP 504 Timeout" error messages when trying to save.

After a bit testing, I get this error even when hitting any "revert" button.

Even when trying to change the "BASE URL OF THE TOWER HOST" in the "SYSTEM" section, I get a timeout.

So I think this is a general problem.

Atm Im running ansible-awx-4.0.0.376-1.el7.x86_64 on CentOS Linux release 7.6.1810 (Core)

kind regards

**Comment by MrMEEE** [comment]
Hi

I have just testet this on a RHEL and CentOS installation.. I don't see the issue..

Do you get any errors???

**Comment by pwe123345** [comment]
I get this error:

ERROR!

Failed to save settings. Returned status: 504

**Comment by MrMEEE** [comment]
Have you checked /var/log/tower/web.log?

**Comment by pwe123345** [comment]
Here is the output:

2019-04-26 12:39:28,014 DEBUG    awx.main.dispatch publish awx.main.tasks.handle_setting_changes(851f6b4f-7b24-4f96-975e-b83ea02380f2, queue=tower_broadcast_all)
Fri Apr 26 14:41:28 2019 - *** HARAKIRI ON WORKER 3 (pid: 7458, try: 1) ***
Fri Apr 26 14:41:28 2019 - HARAKIRI !!! worker 3 status !!!
Fri Apr 26 14:41:28 2019 - HARAKIRI [core 0] <IP> - PATCH /api/v2/settings/all/ since 1556282367
Fri Apr 26 14:41:28 2019 - HARAKIRI !!! end of worker 3 status !!!
DAMN ! worker 3 (pid: 7458) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 3 (new pid: 9475)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x11a7c20 pid: 9475 (default app)

**Comment by MrMEEE** [comment]
Ok.. Hos About /var/log/messages?

**Comment by pwe123345** [comment]
Nothing :(

**Comment by MrMEEE** [comment]
can you try to change the settings with tower-cli??

yum -y install rh-python36-ansible-tower-cli
yum install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36*

scl enable rh-python36 "tower-cli config host http://<awxhost>:8052"
scl enable rh-python36 "tower-cli config username <adminuser>"
scl enable rh-python36 "tower-cli config password <adminpassword>"

scl enable rh-python36 "tower-cli config list"

**Comment by pwe123345** [comment]
Here is the result:

```
[root@bre-awx01 ~]# scl enable rh-python36 "tower-cli config host http://:8052"
Configuration updated successfully.
[root@bre-awx01 ~]# scl enable rh-python36 "tower-cli config username "
username: admin
[root@bre-awx01 ~]# scl enable rh-python36 "tower-cli config password "
password: password
[root@bre-awx01 ~]# scl enable rh-python36 "tower-cli config list"
Error: Invalid configuration option "list".
[root@bre-awx01 ~]# scl enable rh-python36 "tower-cli config"

# User options (set with `tower-cli config`; stored in ~/.tower_cli.cfg).
host: http://:8052
username: admin
password: password
verify_ssl: False

# Global options (set with `tower-cli config --scope=global`, stored in /etc/tower/tower_cli.cfg).
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/tower-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.4', 'console_scripts', 'tower-cli')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/cli/misc.py", line 155, in config
    _echo_setting(option)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/cli/misc.py", line 69, in _echo_setting
    value = getattr(settings, key)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/conf.py", line 234, in __getattr__
    if CONFIG_PARAM_TYPE[key] == click.STRING or CONFIG_PARAM_TYPE[key] == click.Choice:
KeyError: 'server'

```

**Comment by MrMEEE** [comment]
Set host to:
host: http://localhost:8052

**Comment by pwe123345** [comment]
Same result:

[root@bre-awx01 ~]# scl enable rh-python36 "tower-cli config"

# User options (set with `tower-cli config`; stored in ~/.tower_cli.cfg).
host: http://localhost:8052
username: admin
password: password
verify_ssl: False

# Global options (set with `tower-cli config --scope=global`, stored in /etc/tower/tower_cli.cfg).
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/tower-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.4', 'console_scripts', 'tower-cli')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/cli/misc.py", line 155, in config
    _echo_setting(option)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/cli/misc.py", line 69, in _echo_setting
    value = getattr(settings, key)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/conf.py", line 234, in __getattr__
    if CONFIG_PARAM_TYPE[key] == click.STRING or CONFIG_PARAM_TYPE[key] == click.Choice:
KeyError: 'server'

**Comment by MrMEEE** [comment]
This a weird.. and not something I can seem to reproduce... :(..

Are you sure that there is not anything else (like a stacktrace) in web.log??

**Comment by pwe123345** [comment]
I did a new installation. Maybe I did something wrong.
