### ISSUE TITLE
problems whith Initial configuration of AWX

### ISSUE THREAD

**Issue by vladimir2009** [MrMEEE/awx-build#116]
Hi @MrMEEE after installing ansible-awx.x86_64 0:4.0.0.731-1.el7, I stopped at Initial configuration of AWX, after step:
# sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage provision_instance --hostname = $ (hostname)"
I get the following result:
Successfully registered instance awx01
(changed: True)
2019-06-14 07: 10: 17,675 DEBUG awx.main.dispatch publish awx.main.tasks.apply_cluster_membership_policies (80bf7f58-85e1-42c2-b560-101efdd24e5e, queue = awx_private_queue)
I cannot start the next step because the # prompt does not appear.
After ~ 30min, I stop the execution of the command by sending a Ctrl C signal, and I get the following:
^ CTraceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/functional.py", line 42, in __call__
    return self .__ value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During loading

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/transport.py", line 141, in _connect
    host, port, family, socket.SOCK_STREAM, SOL_TCP)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo (host, port, family, type, proto, flags):
socket.gaierror: [Errno -9] Address family for hostname not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/functional.py", line 341, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/connection.py", line 275, in connect
    return self.connection
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/connection.py", line 823, in connection
    self._connection = self._establish_connection()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/connection.py", line 778, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/connection.py", line 307, in connect
    self.transport.connect()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/transport.py", line 81, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/transport.py", line 152, in _connect
    "failed to resolve broker hostname"))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/transport.py", line 165, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==4.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/transaction.py", line 267, in __exit__
    connection.set_autocommit(True)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 416, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 651, in run_and_clear_commit_hooks
    func()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/ha.py", line 268, in <lambda>
    connection.on_commit(lambda: apply_cluster_membership_policies.apply_async())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/dispatch/publish.py", line 103, in apply_async
    routing_key=queue)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/functional.py", line 44, in __call__
    value = self.__value__ = self.__contract__()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 224, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/connection.py", line 852, in default_channel
    self.ensure_connection(**conn_opts)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/functional.py", line 355, in retry_over_time
    sleep(1.0)
KeyboardInterrupt

**Comment by MrMEEE** [comment]
hmmm..

what does

```bash
hostname
hostname -f
```

give you??

**Comment by vladimir2009** [comment]
[root@awx01 ~]# hostname
awx01
[root@awx01 ~]# hostname -f
awx01.ub.kz
[root@awx01 ~]#

**Comment by MrMEEE** [comment]
Got it.. it's because rabbitmq is not running..

I have corrected the documentation.. thanks.. 

I don't think it matters, just continue the installation, I think it will work...

**Comment by vladimir2009** [comment]
Thank you, I will continue ....

**Comment by MrMEEE** [comment]
Please reopen, if you still have issues
