### ISSUE TITLE
awx-manage error

### ISSUE THREAD

**Issue by impsik** [MrMEEE/awx-build#126]
Using Centos7
awx-manage gives me:

`django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: libpq.so.rh-postgresql10-5: cannot open shared object file: No such file or directory`

Full command:
`sudo -u awx /opt/rh/rh-python36/root/usr/bin/awx-manage inventory_import --source=test.txt --inventory-name=Test`

`rpm -aq |grep psycopg2`
`rh-python36-psycopg2-2.7.3.2-1.x86_64`

awx installed using [this link](https://awx.wiki/installation)

Also, i found [this link](https://github.com/MrMEEE/awx-build/issues/108l), but simpli running scl enable rh-postgresql10 rh-python36 "awx-manage" is not doing anything. And there is mentioned "You have to run it with software collections" - english is not my native language and perhaps i just don't understard what needs to be done.

Any hints what could be wrong?

**Comment by impsik** [comment]
What helped me was:
`LD_PRELOAD=/opt/rh/rh-postgresql10/root/usr/lib64/libpq.so.rh-postgresql10-5 /opt/rh/rh-python36/root/usr/bin/awx-manage inventory_import --source=prd.txt --inventory-name=Production`

**Comment by MrMEEE** [comment]
```
scl enable rh-postgresql10 rh-python36 "awx-manage"
```
Is the "right" way to do it.. it works fine her??

What output do you get??

**Comment by impsik** [comment]
Full output:
```
-bash-4.2$ cd /opt/rh/rh-python36/root/usr/bin/
-bash-4.2$ scl enable rh-postgresql10 rh-python36 "awx-manage"

Type 'awx-manage help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[channels]
    runworker

[contenttypes]
    remove_stale_contenttypes

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[django_extensions]
    admin_generator
    clean_pyc
    clear_cache
    compile_pyc
    create_app
    create_command
    create_jobs
    create_template_tags
    delete_squashed_migrations
    describe_form
    drop_test_database
    dumpscript
    export_emails
    find_template
    generate_secret_key
    graph_models
    mail_debug
    merge_model_instances
    notes
    passwd
    pipchecker
    print_settings
    print_user_for_session
    reset_db
    reset_schema
    runjob
    runjobs
    runprofileserver
    runscript
    runserver_plus
    set_default_site
    set_fake_emails
    set_fake_passwords
    shell_plus
    show_template_tags
    show_templatetags
    show_urls
    sqlcreate
    sqldiff
    sqldsn
    sync_s3
    syncdata
    unreferenced_files
    update_permissions
    validate_templates

[main]
    check_license
    check_migrations
    cleanup_activitystream
    cleanup_jobs
    cleanup_sessions
    cleanup_tokens
    create_oauth2_token
    create_preload_data
    deprovision_instance
    expire_sessions
    gather_analytics
    generate_isolated_key
    inventory_import
    list_instances
    profile_sql
    provision_instance
    register_queue
    remove_from_queue
    replay_job_events
    revoke_oauth2_tokens
    run_callback_receiver
    run_dispatcher
    setup_managed_credential_types
    stats
    test_isolated_connection
    unregister_queue
    update_password

[oauth2_provider]
    cleartokens

[rest_framework]
    generateschema

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver
-bash-4.2$ whoami
awx
```

**Comment by MrMEEE** [comment]
It looks like it's working fine???

**Comment by impsik** [comment]
Ok, another full output:
```
-bash-4.2$ cd /opt/rh/rh-python36/root/usr/bin
-bash-4.2$ pwd
/opt/rh/rh-python36/root/usr/bin
-bash-4.2$ ./awx-manage inventory_import --source=test.txt --inventory-name=Test
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 21, in <module>
    import psycopg2 as Database
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq.so.rh-postgresql10-5: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./awx-manage", line 11, in <module>
    load_entry_point('awx==6.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: libpq.so.rh-postgresql10-5: cannot open shared object file: No such file or directory
-bash-4.2$
```

**Comment by MrMEEE** [comment]
It's not supposed to work??

You should always run it with software collections...

Alternatively, you can add
```
scl enable rh-postgresql10 rh-python36 bash
```
to your .bashrc and the software collection will always be enabled

**Comment by impsik** [comment]
Ok, i'm completely retarded because i just can't figure out your comment:
```
You have to run it with software collections:
scl enable rh-postgresql10 rh-python36 "awx-manage"
```
What, how ... that LD_PRELOAD works for me, everything is done what needs to be done, but please explain your comment. I'm totally missing something here ...

**Comment by MrMEEE** [comment]
If it works for you, then it's fine.. :)

if you want to follow the way that I have designed.. you should just run the commands with the software collections command (scl enable rh.........)
e.g:
```
[root@akiva ~]# sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage list_instances"
[tower capacity=57]
        akiva.outerrim.lan capacity=57 version=6.0.0 last_isolated_check="2018-04-28 14:16:18" heartbeat="2019-07-11 16:00:01"

```
or from the awx user:
```
[root@akiva ~]# su - awx
Last login: Sat Jun 22 23:29:41 CEST 2019 on pts/4
-bash-4.2$ scl enable rh-postgresql10 rh-python36 "awx-manage list_instances"
[tower capacity=57]
        akiva.outerrim.lan capacity=57 version=6.0.0 last_isolated_check="2018-04-28 14:16:18" heartbeat="2019-07-11 16:01:01"
```

**Comment by MrMEEE** [comment]
If you want to import your inventory:
as: root
```
sudo -u awx scl enable rh-postgresql10 rh-python36 "awx-manage inventory_import --source=test.txt --inventory-name=Test"
```

**Comment by impsik** [comment]
Yes, that's what is looking for :D
Could you please also document that, because there are a lot of non englis users like me :+1: 
Sorry for the misunderstanding.

**Comment by MrMEEE** [comment]
No problem.. I will put it into the wiki

**Comment by tjyang** [comment]
* For ansible-awx-6.1.0.246, I had to add quiet option.
```
[me@awx01 ~]$ sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage list_instances"
[tower capacity=138]
        awx01 capacity=138 version=6.1.0 last_isolated_check="2018-05-11 16:43:24" heartbeat="2019-08-20 09:57:55"
[me@awx01 ~]$
```

**Comment by MrMEEE** [comment]
@tjyang Do you know what the GIT_PYTHON_REFRESH=quiet option actually does???

**Comment by tjyang** [comment]
@MrMEEE 
I am embarrassed to say , no I don't and I should find out why adding quiet option fix the issue.
Also why rh-git29 dependency got added ...
