### ISSUE TITLE
Problem with sources in awx 

### ISSUE THREAD

**Issue by elsopapa** [MrMEEE/awx-build#131]
No matter which source ive use, always ive get the same error (installed with rpm 6).

[root@bcawx01 ~]# ansible --version
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

[root@bcawx01 ~]# rpm -qa | grep awx
awx-2.1.2.1-1.el7.x86_64

Centos 7. 

Error at importing json or any script
Traceback (most recent call last): File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 994, in handle self.is_custom) File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 245, in load_inventory_source is_custom=is_custom).load() File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 180, in load data = self.command_to_json(base_args + ['--list']) File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json self.method, proc.returncode, stdout, stderr)) RuntimeError: ansible-inventory failed (rc=1) with stdout: stderr: Traceback (most recent call last): File "/bin/ansible-inventory", line 32, in <module> from ansible import context ImportError: cannot import name context

**Comment by MrMEEE** [comment]
Hi..

It looks like you have used the old installation.. The awx rpm is deprecated and replaced by the ansible-awx package..


Have you upgraded?? Have you followed the information on awx.wiki??

**Comment by nkadel** [comment]
The old repository should be deprecated or, ideally, disabled. There are still a number of Google discoverable links pointing to the old repo setup and location, I was just testing something this morning and ran into bad pointers.

**Comment by MrMEEE** [comment]
@nkadel Good idea.. done
