### ISSUE TITLE
"awx-manage migrate" broken after ansible-awx-6.1.0.246-1.el7.x86_64 update

### ISSUE THREAD

**Issue by ekissinger** [MrMEEE/awx-build#142]
Hello, 

getting this error using the standard update commands (centos76):

```
$ sudo -i -u awx scl enable rh-postgresql10 rh-python36 "awx-manage migrate"
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  Applying main.0083_v360_job_branch_override...Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column "scm_refspec" of relation "main_project" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==6.1.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 112, in database_forwards
    field,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 447, in add_field
    self.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "scm_refspec" of relation "main_project" already exists
```

**Comment by MrMEEE** [comment]
@tjyang seems to have found a workaround.. I will look into it later today:

https://github.com/MrMEEE/awx-build/issues/143

**Comment by MrMEEE** [comment]
Oh.. not same error...

This is because the awx team renamed a typo: 

https://github.com/ansible/awx/commit/18a316646b18053a98f9b36e0780d196754f0a2e#diff-c7e1b5004549973bd198a23df6f39785

I'm finding a way around this..

**Comment by MrMEEE** [comment]
Try to run this and afterwards run the migration again:

```
sudo -u postgres scl enable rh-postgresql10 "psql awx -c \"UPDATE django_migrations SET name = '0083_v360_job_branch_override' WHERE name = '0083_v360_job_branch_overrirde'\""
```

**Comment by MrMEEE** [comment]
@ekissinger Did you get this to work?

**Comment by chaleyeah** [comment]
I am getting the same error.  When I attempt to run the command you posted my system tells me I'm not allowed to change into the home directory of the user I'm logged in as.  If I do bad things (this is on my dev server) and sudo -i the command tells me that access is denied in /root.

**Comment by tjyang** [comment]
I got same error about home access denied issue I forgot how I get around
the issue.

**Comment by mjaperta** [comment]
If you change to another folder where the awx user have access (e.g /tmp) before running the command, it doesn't show the warning.. But again, it doesn't fail..??

**Comment by MrMEEE** [comment]
If you change to another folder where the awx user have access (e.g /tmp) before running the command, it doesn't show the warning.. But again, it doesn't fail..??

**Comment by chaleyeah** [comment]
Appreciate the update.  I switched to /tmp and was able to complete the upgrade.  Thanks much!

**Comment by ekissinger** [comment]
> @ekissinger Did you get this to work?

sorry, I've been offline for awhile.  I did get this to work with the psql update command, and it also worked going from 6.1.0.229 to 7.0.0.599

**Comment by MrMEEE** [comment]
Good, thanks for the feedback
