### ISSUE TITLE
Missing configuration page items

### ISSUE THREAD

**Issue by bwosborne2** [MrMEEE/awx-build#145]
The following commands are missing from your configuration page:

- After starting Postgresql "systemctl enable rh-postgresql10-postgresql.service"
- After starting rabbitmq "systemctl enable rabbitmq-server"

Here is what I needed to do for the database import to work.

- Add the awx user to the wheel group in /etc/group
- su - awx
- then run the command on the page as awx user.

- The final nginx command on the page needs to be run as root.
- missing command systemctl start nginx
- missing command systemctl enable nginx

**Comment by MrMEEE** [comment]
Hi..

The enables aren't necessary, as the awx service has these as an requirement..

You shouldn't give the awx root privileges.. it works, if done as described.. what issues are you facing??

**Comment by bwosborne2** [comment]
It does not work as root. If you run as awx user sudo fails.

**Comment by bwosborne2** [comment]
As root:
[root@test-awx02 ~]# sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "awx-manage migrate"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 83, in <module>
    refresh()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/cmd.py", line 290, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==6.1.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/conf/models.py", line 11, in <module>
    from awx.main.models.base import CreatedModifiedModel, prevent_search
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/__init__.py", line 176, in <module>
    activity_stream_registrar.connect(Organization)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/registrar.py", line 14, in connect
    from awx.main.signals import activity_stream_create, activity_stream_update, activity_stream_delete, activity_stream_associate
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/signals.py", line 43, in <module>
    from awx.main.tasks import update_inventory_computed_fields
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 47, in <module>
    import git
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

[root@test-awx02 ~]#

**Comment by bwosborne2** [comment]
as user awx without wheel group:
[root@test-awx02 ~]# su - awx
-bash-4.2$ sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "awx-manage migrate"
awx is not in the sudoers file.  This incident will be reported.
-bash-4.2$

**Comment by MrMEEE** [comment]
You should run this command as the root user

**Comment by MrMEEE** [comment]
and add GIT_PYTHON_REFRESH=quiet

sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"

**Comment by bwosborne2** [comment]
That seems to work with no errors. Hopefully it works on a new installation too. 
Update the docs again?

**Comment by MrMEEE** [comment]
done
