### ISSUE TITLE
Unable to cancel a job in AWX

### ISSUE THREAD

**Issue by kyklos** [MrMEEE/awx-build#152]
I'm unable to cancel a job and got "Error: Call to cancel job failed. POST returned status: 500. A server error has occurred" on AWX 7.0.0.50. Error mesage in web.log

```
2019-09-11 10:17:32,322 ERROR    django.request Internal Server Error: /api/v2/jobs/221/cancel/
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/api/generics.py", line 294, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/api/views/__init__.py", line 3525, in post
    obj.cancel()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 1340, in cancel
    if self.status == 'running' and not self.actually_running:
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 1309, in actually_running
    ).running(timeout=timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/dispatch/control.py", line 37, in running
    return self.control_with_reply('running', *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/dispatch/control.py", line 44, in control_with_reply
    with Consumer(conn, reply_queue, callbacks=[self.process_message], no_ack=True):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 408, in revive
    self.declare()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 421, in declare
    queue.declare()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/entity.py", line 608, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/entity.py", line 617, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/entity.py", line 652, in queue_declare
    nowait=nowait,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/dispatch/kombu.py", line 23, in queue_declare
    return super(_Channel, self).queue_declare(queue, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/channel.py", line 1154, in queue_declare
    spec.Queue.DeclareOk, returns_tuple=True,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/abstract_channel.py", line 80, in wait
    self.connection.drain_events(timeout=timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/connection.py", line 506, in blocking_read
    return self.on_inbound_frame(frame)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/connection.py", line 510, in on_inbound_method
    method_sig, payload, content,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/abstract_channel.py", line 126, in dispatch_method
    listener(*args)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/channel.py", line 282, in _on_close
    reply_code, reply_text, (class_id, method_id), ChannelError,
amqp.exceptions.AccessRefused: Queue.declare: (403) ACCESS_REFUSED - queue name 'amq.rabbitmq.reply-to' contains reserved prefix 'amq.*'
```

**Comment by MrMEEE** [comment]
hmmm.. weird...

Is everything else working??

Are you running cluster or single instance??

**Comment by kyklos** [comment]
It's single instance and everything else is working.

**Comment by yuliy-m** [comment]
Hi @MrMEEE 
I just was able to reproduce the issue. Could please help?

**Comment by MrMEEE** [comment]
Can you reproduce this on version 9.1.1?

**Comment by yuliy-m** [comment]
Hi @MrMEEE Unfortunately I have no 9.1.1 yet. Just a question what version rabbitmq-server is expected?

**Comment by MrMEEE** [comment]
```
[root@akiva ~]# rpm -aq rabbitmq-server
rabbitmq-server-3.7.23-1.el7.noarch
```

**Comment by om22** [comment]
Had exactly the same problem and noticed that our own repos offered rabbitmq-server 3.3.5. After updating to 3.7.24 everything is working fine. Give that a try

**Comment by de1ayer** [comment]
Confirm @om22 notice. After upgrading rabbitmq-server from 3.3.5 to 3.6.16 on my CentOS7 instance job cancelling works again
