### ISSUE TITLE
Ansible AWX - awx-manage migrate issue

### ISSUE THREAD

**Issue by RajaShankar** [MrMEEE/awx-build#153]
Hi MrMEEE,

I am new to Ansible AWX installtion and i have followed your step to configure it but am getting below error on the the step while executing the command 'sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate" '. Please help me to get this fixed

# sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==7.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 126, in manage
    prepare_env()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 91, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/settings/production.py", line 13, in <module>
    from split_settings.tools import optional, include
ModuleNotFoundError: No module named 'split_settings'

**Comment by MrMEEE** [comment]
Which installation instructions have you followed???

It seems like you are missing the dependencies...

**Comment by MrMEEE** [comment]
https://awx.wiki/installation

**Comment by RajaShankar** [comment]
I have followed this one "https://github.com/MrMEEE/awx-build/blob/master/installguide.md"

**Comment by RajaShankar** [comment]
I am trying to install without docker and all the dependencies have been installed.. is there any way to check the dependencies

**Comment by RajaShankar** [comment]
I have reinstalled freshly but still end up with same error.
sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==7.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 126, in manage
    prepare_env()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 91, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/settings/production.py", line 14, in <module>
    from split_settings.tools import optional, include
ModuleNotFoundError: No module named 'split_settings

**Comment by MrMEEE** [comment]
https://github.com/MrMEEE/awx-build/blob/master/installguide.md is not valid anymore..

I'm pretty sure that the dependency installation is failling.. 

Are you on RHEL or CentOS?

/Martin

**Comment by RajaShankar** [comment]
I am trying to install and configure in Centos7. Can you please give me the correct installation link. If that's not valid means.

**Comment by RajaShankar** [comment]
Do i have to install on docker and the configure AWX. can't i install on base os (centos) itself without dockerized environment?

**Comment by mjaperta** [comment]
I have already sent the link: https://awx.wiki/installation

Docker is only needed for AWX.. AWX-RPM is for installing directly on the OS..

**Comment by MrMEEE** [comment]
I have already sent the link: https://awx.wiki/installation

Docker is only needed for AWX.. AWX-RPM is for installing directly on the OS..

**Comment by RajaShankar** [comment]
I have already tried with awx-rpm but still I am getting same error where django split setting module not found..
Please help me to fix it

**Comment by MrMEEE** [comment]
Try to run:
```
yum -y install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base' -x *-debuginfo rh-python36*
```
And send me the output..

**Comment by RajaShankar** [comment]
I couldn't find any direct installation steps of AWX-RPM on the given link. Could you please guide me. Alos i have run the above given command and installed all the packages. Post that i have run the same command(sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate") but getting below error.


 sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage migrate"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 83, in <module>
    refresh()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/cmd.py", line 290, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==7.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/conf/models.py", line 11, in <module>
    from awx.main.models.base import CreatedModifiedModel, prevent_search
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/__init__.py", line 180, in <module>
    activity_stream_registrar.connect(Organization)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/registrar.py", line 14, in connect
    from awx.main.signals import activity_stream_create, activity_stream_update, activity_stream_delete, activity_stream_associate
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/signals.py", line 43, in <module>
    from awx.main.tasks import update_inventory_computed_fields
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 47, in <module>
    import git
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

**Comment by MrMEEE** [comment]
Please look at https://awx.wiki/installation again..

The installations steps are to the right...

**Comment by RajaShankar** [comment]
I am getting below error.

[root@ansible conf]# sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
Unable to open /etc/scl/conf/rh-git29!
****

**Comment by RajaShankar** [comment]
Hello MrMEEE,
Thank you so much for the guidance. Post configuring updated repo, I am able to install all the necessary packages after that issue got fixed.

**Comment by MrMEEE** [comment]
Cool.. Thanks for the feedback
