### ISSUE TITLE
Installing AWX with external DB

### ISSUE THREAD

**Issue by yourkucing** [MrMEEE/awx-build#154]
Hi, I wanted to connect my AWX app server with an external DB but I have been running into errors that says "Error loading psycopg2 module: libpq.so.rh-postgresql10-5: cannot open shared object file: No such file or directory".

I might have configured it wrongly.
This is what I changed in /etc/tower/settings.py

DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'awx',
        'USER': 'awx',
        'PASSWORD': 'password',
        'HOST': '172.31.3.201',
        'PORT': '5432',
    }
}

The error that I get is this:

[root@appserver bin]# /opt/rh/rh-python36/root/usr/bin/awx-manage migrate
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 20, in <module>
    import psycopg2 as Database
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq.so.rh-postgresql10-5: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==7.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 24, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: libpq.so.rh-postgresql10-5: cannot open shared object file: No such file or directory

**Comment by MrMEEE** [comment]
Please use the complete command line for awx-manage:
https://www.awx.wiki/installation/configuration

```sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"```

**Comment by yourkucing** [comment]
It said:
/opt/rh/rh-postgresql10/ doesn't exist

Because i installed postgres on a separate database.

**Comment by MrMEEE** [comment]
Ahhh..

You'll still need the client libraries installed

**Comment by yourkucing** [comment]
This is the error I run into after installing the client libraries:

[root@appserver ~]# sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
warning: /opt/rh/rh-postgresql10//enable scriptlet does not exist!

**Comment by MrMEEE** [comment]
What exactly have you installed??

**Comment by yourkucing** [comment]
I installed according to awx.wiki/installation
The only thing I changed was one of the repo for RHEL7 x86_64, which was originally:
rpm -ivh http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-rh-2-2.el7.centos.noarch.rpm
But since the URL couldn't be found, I googled and found the updates package which is:
http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-rh-2-3.el7.centos.noarch.rpm 

After that, everything else I followed according to the steps until the DB initialisation. Do I still have to initialise the DB?

I apologise for the hassle, I have never attempted to install DB and app separately so I am quite confused :/

**Comment by MrMEEE** [comment]
It seems like you have not installed the rh-postgresql libraries.. 

Try a 
```
yum -y install rh-postgresql10
```

And yes, you still need to initialize the database with the awx-manage migrate command..

**Comment by yourkucing** [comment]
It has been installed already.

[root@appserver ~]# yum -y install rh-postgresql10
Loaded plugins: amazon-id, product-id, rhui-lb, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Package rh-postgresql10-3.1-1.el7.x86_64 already installed and latest version
Nothing to do

**Comment by powertim** [comment]
Hi,

I would say that you don't have the right version of postgresql:

> ImportError: libpq.so.rh-postgresql**10-5**: cannot open shared object file: No such file or directory
> Package rh-postgresql**10-3**.1-1.el7.x86_64 already installed and latest version

My playbook may help you to achieve your goal, unfortunately I didn't have time to update it to match the 6.1.0 & 7.0.0 version of AWX, but it could be a start: https://github.com/powertim/deploy_awx-rpm

Cheers,

Tim.

**Comment by MrMEEE** [comment]
Ahh  @powertim, well spotted...

@yourkucing are you running CentOS or RHEL???

**Comment by yourkucing** [comment]
> Hi,
> 
> I would say that you don't have the right version of postgresql:
> 
> > ImportError: libpq.so.rh-postgresql**10-5**: cannot open shared object file: No such file or directory
> > Package rh-postgresql**10-3**.1-1.el7.x86_64 already installed and latest version
> 
> My playbook may help you to achieve your goal, unfortunately I didn't have time to update it to match the 6.1.0 & 7.0.0 version of AWX, but it could be a start: https://github.com/powertim/deploy_awx-rpm
> 
> Cheers,
> 
> Tim.

Thank you very much, Tim. I'll give it a try. :)

**Comment by yourkucing** [comment]
> Ahh @powertim, well spotted...
> 
> @yourkucing are you running CentOS or RHEL???

I'm using RHEL7.5

**Comment by MrMEEE** [comment]
Try adding this repo:
http://ftp.iij.ad.jp/pub/linux/centos/7/sclo/x86_64/rh/

**Comment by MrMEEE** [comment]
Did you get it to work??

**Comment by refriedjello** [comment]
I am also using a dedicated/external database and was able to get around this with these steps, on CentOS 7:

```
sudo yum -y install rh-postgresql10-postgresql-libs
sudo ln -s /opt/rh/rh-postgresql10/root/usr/lib64/libpq.so.rh-postgresql10-5 /usr/lib/libpq.so.rh-postgresql10-5
sudo ln -s /opt/rh/rh-postgresql10/root/usr/lib64/libpq.so.rh-postgresql10-5 /usr/lib64/libpq.so.rh-postgresql10-5
```

**Comment by refriedjello** [comment]
I was able to get an (apparently) working setup of AWX using an external database. I have just poked around the WebUI so far, and have not yet imported an inventory or run a template.

However, even though I did not install postgres on the same server as AWX, it appears there are still references to that in places, by various awx* services.

Should all references to 'postgres' be removed from these files under /usr/lib/systemd/system ?

```
awx-cbreceiver.service:ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 "awx-manage run_callback_receiver"
awx-channels-worker.service:ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 "awx-manage runworker --only-channels 'websocket.*'"
awx-daphne.service:ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 "daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer"
awx-dispatcher.service:ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 "awx-manage run_dispatcher"
awx.service:Requires=awx-cbreceiver.service awx-daphne.service awx-dispatcher.service awx-channels-worker.service awx-web.service nginx.service rh-postgresql10-postgresql.service memcached.service rabbitmq-server.service
awx-web.service:ExecStart=/usr/bin/scl enable rh-python36 rh-postgresql10 "uwsgi \
```

@MrMEEE the custom note you sent me on LinkedIn just said to copy and modify "/usr/lib/systemd/system/awx.service". This is what I did:

```
sudo cp /usr/lib/systemd/system/awx.service /etc/systemd/system/awx.service
sudo vi /etc/systemd/system/awx.service
# note: remove "rh-postgresql10-postgresql.service" and "memcached.service" from the "Requires" line
```

**Comment by MrMEEE** [comment]
You shouldn't have to do the symlinks? 

Only the requirement in awx.service should be removed.. All the others are to use the correct postgres client libraries..

**Comment by soonho36** [comment]
Hello. I also got an error while trying to install from an external repository.

[root@tower1 ~]# cat /etc/hosts
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

192.168.101.200 tower1.lab
192.168.101.203 towerdb.lab
```

[root@tower1 ~]# cat /etc/tower/settings.py
```
~~~
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'awx',
        # 'USER': os.getenv("DATABASE_USER", None),
        # 'PASSWORD': os.getenv("DATABASE_PASSWORD", None),
        # 'HOST': os.getenv("DATABASE_HOST", None),
        # 'PORT': os.getenv("DATABASE_PORT", None),
        'USER': 'admin',
        'PASSWORD': 'password',
        'HOST': '192.168.101.203',
        'PORT': '5432',
    }
}
~~~
```



[root@tower1 ~]# sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "192.168.101.203" and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.1.1', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "192.168.101.203" and accepting
	TCP/IP connections on port 5432?
```

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
