### ISSUE TITLE
Unable to execute Dynamic Inventory Script

### ISSUE THREAD

**Issue by EdHunter87** [MrMEEE/awx-build#167]
We are running an inventory script from a project that pulls data from our source of truth. On a base install of AWX we create a virtual python environment under `/var/lib/awx/venv`. I did the same thing on the AWX-RPM install, but I am getting a traceback error. 

The script is marked as executable and as pointer to the virtual environment. I have tested the script local on the AWX-RPM server and it executes as executed. Only fails when running from a job. 

Adding the script to the Inventory script section does not work either. Seems to be related to the rh-python36 

Traceback:
```2.040 INFO     Updating inventory 3: etcd_inv
    2.892 INFO     Reading Ansible inventory source: /tmp/awx_6_vl_4o0mq/tmptac2la_8
    2.894 INFO     Using VIRTUAL_ENV: /opt/rh/rh-python36/root/
    2.894 INFO     Using PATH: /opt/rh/rh-python36/root/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-postgresql10/root/usr/bin:/opt/rh/rh-python36/root/usr/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    2.894 INFO     Using PYTHONPATH: /opt/rh/rh-python36/root/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==7.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 142, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1153, in handle
    raise exc
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1043, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 214, in load
    return self.command_to_json(base_args + ['--list'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 197, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible
  executable location = /opt/rh/rh-python36/root/bin/ansible-inventory
  python version = 3.6.3 (default, May 31 2019, 13:05:43) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /tmp/awx_6_vl_4o0mq/tmptac2la_8 as it did not pass it's verify_file() method
auto declined parsing /tmp/awx_6_vl_4o0mq/tmptac2la_8 as it did not pass it's verify_file() method
toml declined parsing /tmp/awx_6_vl_4o0mq/tmptac2la_8 as it did not pass it's verify_file() method
 [WARNING]:  * Failed to parse /tmp/awx_6_vl_4o0mq/tmptac2la_8 with script
plugin: problem running /tmp/awx_6_vl_4o0mq/tmptac2la_8 --list ([Errno 2] No
such file or directory: '/tmp/awx_6_vl_4o0mq/tmptac2la_8':
'/tmp/awx_6_vl_4o0mq/tmptac2la_8')
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))
 [WARNING]:  * Failed to parse /tmp/awx_6_vl_4o0mq/tmptac2la_8 with yaml
plugin: Syntax Error while loading YAML.   expected '<document start>', but
found '<scalar>'  The error appears to be in '/tmp/awx_6_vl_4o0mq/tmptac2la_8':
line 19, column 1, but may be elsewhere in the file depending on the exact
syntax problem.  The offending line appears to be:   import sys ^ here
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/inventory/yaml.py", line 105, in parse
    raise AnsibleParserError(e)
 [WARNING]:  * Failed to parse /tmp/awx_6_vl_4o0mq/tmptac2la_8 with ini plugin:
/tmp/awx_6_vl_4o0mq/tmptac2la_8:3: Error parsing host definition ''''': No
closing quotation
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
 [WARNING]: Unable to parse /tmp/awx_6_vl_4o0mq/tmptac2la_8 as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.```

Any help would be greatly appreciated

**Comment by EdHunter87** [comment]
I had to select the correct `Ansible Environment` from the source tab. Script is working as expected now.

Closing
