### ISSUE TITLE
Broken job after upgrading to v8

### ISSUE THREAD

**Issue by Neurozone** [MrMEEE/awx-build#173]
OUTPUT of job:

Traceback (most recent call last): 
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) 
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) 
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj' 
During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 1381, in run res = ansible_runner.interface.run(**params) File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/interface.py", line 178, in run r.run() File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 262, in run _delete() File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 258, in _delete res = _delete(retries=retries - 1) 
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 258, in _delete res = _delete(retries=retries - 1) File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 258, in _delete res = _delete(retries=retries - 1) 
[Previous line repeated 11 more times] File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) 
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) 
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) 
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_1296_sq82fygj'

I don't really understand what is causing this error

**Comment by MrMEEE** [comment]
Have you looked at: https://github.com/MrMEEE/awx-build/issues/163 and the workaround?

**Comment by Neurozone** [comment]
> 
> 
> Have you looked at: #163 and the workaround?

Hahaha jut saw this one. I will try it and let you know :)
You're fast !

**Comment by Neurozone** [comment]
The job was running fine after the workaround !
Closing the issue :)
