### ISSUE TITLE
Syncing broken between awx and foreman

### ISSUE THREAD

**Issue by Neurozone** [MrMEEE/awx-build#174]
2.922 INFO     Updating inventory 8: foreman
    4.097 INFO     Reading Ansible inventory source: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/foreman.py
    4.100 INFO     Using VIRTUAL_ENV: /opt/rh/rh-python36/root/
    4.101 INFO     Using PATH: /opt/rh/rh-python36/root/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-postgresql10/root/usr/bin:/opt/rh/rh-python36/root/usr/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    4.101 INFO     Using PYTHONPATH: /opt/rh/rh-python36/root/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==8.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 158, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1153, in handle
    raise exc
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1043, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 214, in load
    return self.command_to_json(base_args + ['--list'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 197, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
bwrap: Can't find source path /var/lib/awx/venv/awx: No such file or directory

Seems related to a missing link ?

**Comment by MrMEEE** [comment]
does the link exist?
```
ls -la /var/lib/awx/venv
```
It's supposed to point to:
/opt/rh/rh-python36/root

**Comment by Neurozone** [comment]
ls -la /var/lib/awx/venv
total 8
drwxr-x--- 2 awx awx 4096 Oct 22 10:59 .
drwxr-x--- 9 awx awx 4096 Oct 22 13:13 ..

no ^^

now :

ll
total 0
lrwxrwxrwx 1 root root 24 Oct 22 14:17 awx -> /opt/rh/rh-python36/root

**Comment by MrMEEE** [comment]
That is weird... does it work now?

**Comment by Neurozone** [comment]
yes 👍 warnings   InsecureRequestWarning, /opt/rh/rh-python36/root/lib/python3.6/site-
   60.995 ERROR    packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified
   60.995 ERROR    HTTPS request is being made. Adding certificate verification is strongly
   60.995 ERROR    advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-

**Comment by MrMEEE** [comment]
cool
