### ISSUE TITLE
ansible-tower-cli: pkg_resources.DistributionNotFound: colorama>=0.3.1

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#19]
@MrMEEE , Looks like ansible-tower-cli is missing  python-colorama pkg dependency.
```
[root@awx01 awx]# yum install ansible-tower-cli -y
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.aol.com
 * epel: mirror.math.princeton.edu
 * extras: mirror.math.princeton.edu
 * updates: repos-va.psychz.net
Resolving Dependencies
--> Running transaction check
---> Package ansible-tower-cli.noarch 0:3.3.0-2.el7.centos will be installed
--> Processing Dependency: python-click >= 2.1 for package: ansible-tower-cli-3.3.0-2.el7.centos.noarch
--> Running transaction check
---> Package python2-click.noarch 0:6.7-6.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================================================================
 Package                                       Arch                               Version                                          Repository                                  Size
====================================================================================================================================================================================
Installing:
 ansible-tower-cli                             noarch                             3.3.0-2.el7.centos                               mrmeee-awx-dev                             197 k
Installing for dependencies:
 python2-click                                 noarch                             6.7-6.el7                                        epel                                       126 k

Transaction Summary
====================================================================================================================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 323 k
Installed size: 1.4 M
Downloading packages:
(1/2): python2-click-6.7-6.el7.noarch.rpm                                                                                                                    | 126 kB  00:00:00
(2/2): ansible-tower-cli-3.3.0-2.el7.centos.noarch.rpm                                                                                                       | 197 kB  00:00:00
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                               493 kB/s | 323 kB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python2-click-6.7-6.el7.noarch                                                                                                                                   1/2
  Installing : ansible-tower-cli-3.3.0-2.el7.centos.noarch                                                                                                                      2/2
  Verifying  : ansible-tower-cli-3.3.0-2.el7.centos.noarch                                                                                                                      1/2
  Verifying  : python2-click-6.7-6.el7.noarch                                                                                                                                   2/2

Installed:
  ansible-tower-cli.noarch 0:3.3.0-2.el7.centos

Dependency Installed:
  python2-click.noarch 0:6.7-6.el7

Complete!
[root@awx01 awx]# tower-cli --help
Traceback (most recent call last):
  File "/usr/bin/tower-cli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: colorama>=0.3.1
[root@awx01 awx]#
```
* Fix is to install following 
```
 yum install -y python-colorama.noarch
```

**Comment by MrMEEE** [comment]
Thanks for the info...

This should be fixed now :)
