### ISSUE TITLE
psycopg2.errors.DuplicateColumn

### ISSUE THREAD

**Issue by dominiquearpin** [MrMEEE/awx-build#190]
Hi,

Hi tried to upgrade from ansible-awx-9.0.1.94-1.el7.x86_64.rpm to ansible-awx-9.0.1.256-1.el7.x86_64.rpm

But I get this error:
```
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  Applying main.0100_v370_projectupdate_job_tags...Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "job_tags" of relation "main_projectupdate" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.0.1', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 158, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 112, in database_forwards
    field,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 447, in add_field
    self.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "job_tags" of relation "main_projectupdate" already exists

```
Regards,

**Comment by MrMEEE** [comment]
I hope to get time to look at this wednesday...

**Comment by MrMEEE** [comment]
I have just upgraded from ansible-awx-8.0.0.54-1.el7.x86_64 to ansible-awx-9.0.1.262-1.el7.x86_64 without any issues.. Have you a backup, so that you can roll back and try again??

**Comment by marcosshpak** [comment]
For me, same problem occurred for version ansible-awx-9.0.1.142-1.el7.x86_64 -> ansible-awx-9.0.1.270-1.el7.x86_64.rpm
Looking at the django log, you can see that the problem is due to a column from the "main_projectupdate" table.
In my case, I don't use this table, so I performed the following steps;
I connect in base awx and deleted the job_tags column
postgres=# alter table main_projectupdate drop column job_tags;

after erasing the column, apply the scl de migrate command.
If you choose to perform the same procedure, backup database first.

**Comment by MrMEEE** [comment]
@marcosshpak Thanks for the feedback.. Seems this is only between certains releases..

**Comment by dominiquearpin** [comment]
@marcosshpak : thanks is working perfectly

here the step, if someone need it:
`sudo -u postgres -i`
`-bash-4.2$ scl enable rh-postgresql10 "psql"`
`postgres=# \c awx`
`awx=# alter table main_projectupdate drop column job_tags;`
`ALTER TABLE`
`awx=# \q`
`-bash-4.2$ exit`
`logout`

**Comment by unixsysadmin** [comment]
Issue seen upgrading from 9.0.1.67-1 to 9.1.0.84-1

Used the workaround https://github.com/MrMEEE/awx-build/issues/190#issuecomment-561717772 to drop the job_tags column and then re-ran:

`sudo -u awx scl enable rh-postgresql10 rh-python36 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"`

Thanks @dominiquearpin and @marcosshpak !

**Comment by chaleyeah** [comment]
Adding another +1 for this.  I was going from 9.0.1.67-1 to 9.2 and had the same issues.  The comment above about fixing the DB resolved my issues.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
