### ISSUE TITLE
9.0.1.347 from 9.0.1.142-1 upgrade failed

### ISSUE THREAD

**Issue by tjyang** [MrMEEE/awx-build#193]
*  failed at awx-manage migrate step.
```
[root@awx01 ~]# sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage makemigrations"

No changes detected
[root@awx01 ~]#
[root@awx01 ~]# sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"

Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  Applying main.0099_v361_license_cleanup... OK
  Applying main.0100_v370_projectupdate_job_tags...Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "job_tags" of relation "main_projectupdate" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.0.1', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 165, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 112, in database_forwards
    field,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 447, in add_field
    self.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "job_tags" of relation "main_projectupdate" already exists

[root@awx01 ~]# date
Wed Dec 11 09:39:54 EST 2019
[root@awx01 ~]#


```
* login screenshot.
![image](https://user-images.githubusercontent.com/378638/70631432-c76bfc80-1bf2-11ea-8c3f-4e850332c2f5.png)

* /var/log/tower/web.log
```
<snipped>
[pid: 2250|app: 0|req: 28/275] 192.168.1.108 () {44 vars in 2457 bytes} [Wed Dec 11 14:45:57 2019] GET /api/v2/config/ => generated 0 bytes in 25 msecs (HTTP/1.1 302) 3 headers in 119 bytes (1 switches on core 0)
[pid: 2249|app: 0|req: 142/276] 192.168.1.108 () {46 vars in 2459 bytes} [Wed Dec 11 14:45:57 2019] GET /api/ => generated 0 bytes in 25 msecs (HTTP/1.1 302) 3 headers in 119 bytes (1 switches on core 0)
[pid: 2246|app: 0|req: 26/277] 192.168.1.108 () {44 vars in 2534 bytes} [Wed Dec 11 14:45:57 2019] GET /api/v2/workflow_approvals/?status=pending&page_size=1 => generated 0 bytes in 25 msecs (HTTP/1.1 302) 3 headers in 119 bytes (1 switches on core 0)
[pid: 2249|app: 0|req: 143/278] 192.168.1.108 () {44 vars in 2487 bytes} [Wed Dec 11 14:45:57 2019] GET /migrations_notran/ => generated 1404 bytes in 47 msecs (HTTP/1.1 200) 7 headers in 343 bytes (1 switches on core 0)
[pid: 2249|app: 0|req: 144/279] 192.168.1.108 () {46 vars in 2509 bytes} [Wed Dec 11 14:45:58 2019] GET /migrations_notran/ => generated 1404 bytes in 44 msecs (HTTP/1.1 200) 7 headers in 343 bytes (1 switches on core 0)
[pid: 2249|app: 0|req: 145/280] 192.168.1.108 () {44 vars in 2487 bytes} [Wed Dec 11 14:45:58 2019] GET /migrations_notran/ => generated 1404 bytes in 58 msecs (HTTP/1.1 200) 7 headers in 343 bytes (1 switches on core 0)


```

**Comment by MrMEEE** [comment]
https://github.com/MrMEEE/awx-build/issues/190

**Comment by tjyang** [comment]
* Thanks for the quick response. job_tags column was dropped to enable successful migrate action.
```
[pi@awx01 ~]$  sudo -u postgres -i
-bash-4.2$ scl enable rh-postgresql10 "psql"
psql (10.6)
Type "help" for help.

postgres=# \c awx
You are now connected to database "awx" as user "postgres".
awx=#  alter table main_projectupdate drop column job_tags;
ALTER TABLE
awx=# \q
-bash-4.2$ exit
logout
[pi@awx01 ~]$ sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  Applying main.0100_v370_projectupdate_job_tags... OK
[pi@awx01 ~]$ date
Wed Dec 11 10:28:03 EST 2019
[pi@awx01 ~]$

```
