### ISSUE TITLE
Block object has no attribute 'get_name'

### ISSUE THREAD

**Issue by EdHunter87** [MrMEEE/awx-build#200]
I have a job that runs against 800ish servers, to make sure the configuration is still configured to our standards. This job will run fine on the Docker version of AWX, but when trying to run on this rpm version I am seeing an error randomly. 

Here is the error when debugging is turned on.
```
ERROR! Unexpected Exception, this is probably a bug: 'Block' object has no attribute 'get_name'
the full traceback was:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/executor/task_queue_manager.py", line 240, in run
    play_return = strategy.run(iterator, play_context)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/strategy/free.py", line 188, in run
    self._execute_meta(task, play_context, iterator, target_host=host)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/strategy/__init__.py", line 1052, in _execute_meta
    self.run_handlers(iterator, play_context)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/strategy/__init__.py", line 899, in run_handlers
    result = self._do_handler_run(handler, handler.get_name(), iterator=iterator, play_context=play_context)
  File "/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/strategy/__init__.py", line 968, in _do_handler_run
    task_name = task.get_name()
AttributeError: 'Block' object has no attribute 'get_name'
```

I have updated all the rh-python36 packages following the awxrpm documentation, I have even tried removing and re-adding the rh-python36 packages. 

Any thoughts on what could be causing the issue?

Thanks in advance

**Comment by MrMEEE** [comment]
Have you tried using a python2 venv to run this???

**Comment by EdHunter87** [comment]
I have not, I only have your default rh-python36 environment setup up. Is there a good location that would show all the packages I need to setup a python2 environment and test this?

**Comment by MrMEEE** [comment]
Have you tried awx-create-venv?

https://awx.wiki/tools/awx-create-venv

**Comment by EdHunter87** [comment]
I have created a ansible 2 awx version following the documentation on that page. I got the same error, but didn't have debug logging on. I am running another run of the job now with debugging to get the error output again. 

---
Here is the error output:

```
ERROR! Unexpected Exception, this is probably a bug: 'Block' object has no attribute 'get_name'
the full traceback was:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx-python2/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/var/lib/awx/venv/awx-python2/lib/python2.7/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/var/lib/awx/venv/awx-python2/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/var/lib/awx/venv/awx-python2/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 240, in run
    play_return = strategy.run(iterator, play_context)
  File "/var/lib/awx/venv/awx-python2/lib/python2.7/site-packages/ansible/plugins/strategy/free.py", line 188, in run
    self._execute_meta(task, play_context, iterator, target_host=host)
  File "/var/lib/awx/venv/awx-python2/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 1052, in _execute_meta
    self.run_handlers(iterator, play_context)
  File "/var/lib/awx/venv/awx-python2/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 899, in run_handlers
    result = self._do_handler_run(handler, handler.get_name(), iterator=iterator, play_context=play_context)
  File "/var/lib/awx/venv/awx-python2/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 968, in _do_handler_run
    task_name = task.get_name()
AttributeError: 'Block' object has no attribute 'get_name'
```

**Comment by MrMEEE** [comment]
Can you show me an example from the playbook?

**Comment by EdHunter87** [comment]
I reverted my playbook then recommited the code and it is not running as expected. Must be something within the original code that was breaking it. 

Thanks for the help, I am closing this post
