### ISSUE TITLE
uWSGI issues after updating to latest AWX 9.0.1.262 version

### ISSUE THREAD

**Issue by kyklos** [MrMEEE/awx-build#209]
I have some trouble that after updating to latest AWX 9.0.1.262 version uWSGI seems to crash quite after the start of AWX. Any idea?

> *** Starting uWSGI 2.0.18 (64bit) on [Mon Jan 20 09:27:47 2020] ***
> compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 13 January 2020 10:33:33
> os: Linux-3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019
> nodename: deddinfra01
> machine: x86_64
> clock source: unix
> pcre jit disabled
> detected number of CPU cores: 2
> current working directory: /
> detected binary path: /opt/rh/rh-python36/root/usr/bin/uwsgi
> setgid() to 991
> setuid() to 993
> your processes number limit is 15072
> your memory page size is 4096 bytes
>  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers ***
> detected max file descriptor number: 1024
> lock engine: pthread robust mutexes
> thunder lock: disabled (you can enable it with --thunder-lock)
> uwsgi socket 0 bound to TCP address 127.0.0.1:8050 fd 3
> Python version: 3.6.9 (default, Nov 11 2019, 11:24:16)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
> *** Python threads support is disabled. You can enable it with --enable-threads ***
> Python main interpreter initialized at 0x1da06f0
> your server socket listen backlog is limited to 100 connections
> your mercy for graceful operations on workers is 60 seconds
> mapped 609552 bytes (595 KB) for 5 cores
> *** Operational MODE: preforking ***
> *** uWSGI is running in multiple interpreter mode ***
> spawned uWSGI master process (pid: 25445)
> spawned uWSGI worker 1 (pid: 25448, cores: 1)
> spawned uWSGI worker 2 (pid: 25449, cores: 1)
> spawned uWSGI worker 3 (pid: 25450, cores: 1)
> spawned uWSGI worker 4 (pid: 25451, cores: 1)
> spawned uWSGI worker 5 (pid: 25452, cores: 1)
> WSGI app 0 (mountpoint='') ready in 8 seconds on interpreter 0x1da06f0 pid: 25448 (default app)
> WSGI app 0 (mountpoint='') ready in 8 seconds on interpreter 0x1da06f0 pid: 25451 (default app)
> WSGI app 0 (mountpoint='') ready in 8 seconds on interpreter 0x1da06f0 pid: 25450 (default app)
> WSGI app 0 (mountpoint='') ready in 9 seconds on interpreter 0x1da06f0 pid: 25452 (default app)
> [pid: 25448|app: 0|req: 1/1] 192.168.1.75 () {44 vars in 2384 bytes} [Mon Jan 20 08:27:56 2020] GET / => generated 11361 bytes in 1221 msecs (HTTP/2.0 200) 7 headers in 334 bytes (1 switches on core 0)
> WSGI app 0 (mountpoint='') ready in 9 seconds on interpreter 0x1da06f0 pid: 25449 (default app)
> [pid: 25450|app: 0|req: 1/2] 192.168.1.75 () {44 vars in 2317 bytes} [Mon Jan 20 08:27:57 2020] GET /api/ => generated 186 bytes in 1023 msecs (HTTP/2.0 200) 11 headers in 533 bytes (1 switches on core 0)
> [pid: 25451|app: 0|req: 1/3] 192.168.1.75 () {44 vars in 2444 bytes} [Mon Jan 20 08:27:58 2020] GET /api/v2/workflow_approvals/?status=pending&page_size=1 => generated 52 bytes in 915 msecs (HTTP/2.0 200) 10 headers in 427 bytes (1 switches on core 0)
> [pid: 25449|app: 0|req: 1/4] 192.168.1.75 () {46 vars in 2369 bytes} [Mon Jan 20 08:27:58 2020] GET /api/ => generated 186 bytes in 990 msecs (HTTP/2.0 200) 11 headers in 533 bytes (1 switches on core 0)
> [pid: 25451|app: 0|req: 2/5] 192.168.1.75 () {46 vars in 2358 bytes} [Mon Jan 20 08:27:59 2020] GET /api/v2/ => generated 1688 bytes in 171 msecs (HTTP/2.0 200) 10 headers in 423 bytes (1 switches on core 0)
> [pid: 25449|app: 0|req: 2/6] 192.168.1.75 () {46 vars in 2462 bytes} [Mon Jan 20 08:27:59 2020] GET /api/v2/dashboard/graphs/jobs/?period=month&job_type=all => generated 1124 bytes in 41 msecs (HTTP/2.0 200) 8 headers in 258 bytes (1 switches on core 0)
> [pid: 25452|app: 0|req: 1/7] 192.168.1.75 () {44 vars in 2367 bytes} [Mon Jan 20 08:27:58 2020] GET /api/v2/config/ => generated 727 bytes in 1220 msecs (HTTP/2.0 200) 10 headers in 436 bytes (1 switches on core 0)
> [pid: 25451|app: 0|req: 3/8] 192.168.1.75 () {44 vars in 2350 bytes} [Mon Jan 20 08:27:59 2020] GET /api/v2/config/ => generated 727 bytes in 78 msecs (HTTP/2.0 200) 10 headers in 436 bytes (1 switches on core 0)
> [pid: 25450|app: 0|req: 2/9] 192.168.1.75 () {46 vars in 2387 bytes} [Mon Jan 20 08:27:59 2020] GET /api/v2/dashboard/ => generated 1410 bytes in 99 msecs (HTTP/2.0 200) 9 headers in 353 bytes (1 switches on core 0)
> SIGINT/SIGQUIT received...killing workers...
> worker 1 buried after 0 seconds
> worker 2 buried after 0 seconds
> worker 3 buried after 1 seconds
> worker 4 buried after 1 seconds
> worker 5 buried after 1 seconds
> goodbye to uWSGI.
>

**Comment by kyklos** [comment]
I found a fix based on 

> Jan 20 12:17:41 deddinfra01 systemd: Starting Application...
> Jan 20 12:17:41 deddinfra01 systemd: Started Application.
> Jan 20 12:17:41 deddinfra01 systemd: Started AWX channels worker service.
> Jan 20 12:17:41 deddinfra01 systemd: Started AWX daphne service.
> Jan 20 12:17:41 deddinfra01 systemd: Started AWX Dispatcher.
> Jan 20 12:17:41 deddinfra01 systemd: Started AWX cbreceiver service.
> Jan 20 12:17:41 deddinfra01 systemd: Started AWX web service.
> Jan 20 12:17:51 deddinfra01 scl: Traceback (most recent call last):
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/bin/daphne", line 11, in <module>
> Jan 20 12:17:51 deddinfra01 scl: load_entry_point('daphne==1.3.0', 'console_scripts', 'daphne')()
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/daphne/cli.py", line 144, in entrypoint
> Jan 20 12:17:51 deddinfra01 scl: cls().run(sys.argv[1:])
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/daphne/cli.py", line 174, in run
> Jan 20 12:17:51 deddinfra01 scl: channel_layer = importlib.import_module(module_path)
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
> Jan 20 12:17:51 deddinfra01 scl: return _bootstrap._gcd_import(name[level:], package, level)
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap_external>", line 678, in exec_module
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/asgi.py", line 37, in <module>
> Jan 20 12:17:51 deddinfra01 scl: channel_layer = get_channel_layer()
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/channels/asgi.py", line 118, in get_channel_layer
> Jan 20 12:17:51 deddinfra01 scl: return channel_layers[alias].channel_layer
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/channels/asgi.py", line 70, in __getitem__
> Jan 20 12:17:51 deddinfra01 scl: self.backends[key] = self.make_backend(key)
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/channels/asgi.py", line 33, in make_backend
> Jan 20 12:17:51 deddinfra01 scl: return self._make_backend(name, config)
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/channels/asgi.py", line 48, in _make_backend
> Jan 20 12:17:51 deddinfra01 scl: backend_class = import_string(self.configs[name]['BACKEND'])
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
> Jan 20 12:17:51 deddinfra01 scl: module = import_module(module_path)
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
> Jan 20 12:17:51 deddinfra01 scl: return _bootstrap._gcd_import(name[level:], package, level)
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap_external>", line 678, in exec_module
> Jan 20 12:17:51 deddinfra01 scl: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/asgi_amqp/__init__.py", line 7, in <module>
> Jan 20 12:17:51 deddinfra01 scl: __version__ = pkg_resources.require('asgi_amqp')[0].version
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
> Jan 20 12:17:51 deddinfra01 scl: needed = self.resolve(parse_requirements(requirements))
> Jan 20 12:17:51 deddinfra01 scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
> Jan 20 12:17:51 deddinfra01 scl: raise VersionConflict(dist, req).with_context(dependent_req)
> Jan 20 12:17:51 deddinfra01 scl: pkg_resources.ContextualVersionConflict: (zipp 0.0.0 (/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages), Requirement.parse('zipp>=0.5'), {'importlib-metadata'})
> Jan 20 12:17:51 deddinfra01 scl: 2020-01-20 11:17:51,838 WARNING  awx.main.commands.run_callback_receiver scaling up worker pid:23019
> 
> 

`sudo -u awx scl enable rh-postgresql10 rh-python36 rh-git29 "pip install --upgrade --user zipp"
`
