### ISSUE TITLE
Installation issue - create_preload_data fails AttributeError: 'NoneType' object has no attribute 'username'

### ISSUE THREAD

**Issue by communig8-public** [MrMEEE/awx-build#210]
Using the Installation guide at https://awx.wiki/installation and woking with all the latest software
releases. When I come to the step to create the preload data, I get the following problem...

su - awx

-bash-4.2$ scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage create_preload_data"

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.1.1', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/create_preload_data.py", line 41, in handle
    'username': superuser.username
AttributeError: 'NoneType' object has no attribute 'username'

Any ideas?
Thanks, Richard

**Comment by communig8-public** [comment]
I'm not a Python guy but reading the code in create_preload_data.py, it looks like this will happen if no superuser currently exists?

**Comment by communig8-public** [comment]
Ah sorry, my bad. The previous command in the installation instructions (echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')" | sudo -u awx scl enable rh-python36 rh-postgresql10 "GIT_PYTHON_REFRESH=quiet awx-manage shell") had not run correctly
