### ISSUE TITLE
Awx ansible endless loop when trying to login 

### ISSUE THREAD

**Issue by gefela** [MrMEEE/awx-build#219]
I have the latest version of ansible awx and continues to go into a endless loop when trying to login  ( with a upgrade message )

**Comment by gefela** [comment]
![awx error](https://user-images.githubusercontent.com/30554569/75791053-eb5b5c00-5d63-11ea-9671-f65f1652173d.png)

**Comment by Nekasas** [comment]
you need to run migrate command

sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"

**Comment by gefela** [comment]
I have manage to get it up but still displays 502 Bad gateway error nginx 1.16.1

**Comment by gefela** [comment]
I have manage to get it up but still displays 502 Bad gateway error nginx 1.16.1

**Comment by MrMEEE** [comment]
Did you run the migrate command?... did you follow the upgrade instructions??

**Comment by gefela** [comment]
Yes I did

**Comment by gefela** [comment]
Yes I did . strangely I have now got the gui back but I cannot login . I have set the admin password but I cannot login

**Comment by gefela** [comment]
Yes I did . strangely I have now got the gui back but I cannot login . I have set the admin password but I cannot login

**Comment by MrMEEE** [comment]
https://awx.wiki/tools/reset-admin-password

**Comment by gefela** [comment]
This is what I am getting ...

sudo -u awx scl enable rh-python36 rh-postgresql10 "awx-manage changepassword admin"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 83, in <module>
    refresh()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/cmd.py", line 287, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.2.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/conf/models.py", line 11, in <module>
    from awx.main.models.base import CreatedModifiedModel, prevent_search
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/__init__.py", line 180, in <module>
    activity_stream_registrar.connect(Organization)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/registrar.py", line 14, in connect
    from awx.main.signals import activity_stream_create, activity_stream_update, activity_stream_delete, activity_stream_associate
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/signals.py", line 43, in <module>
    from awx.main.tasks import update_inventory_computed_fields
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 45, in <module>
    import git
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

**Comment by Nekasas** [comment]
its mean that you need to install additional rh-git versions. It was same for me

so for know my migrate command looks like:
sudo -u awx scl enable rh-postgresql10 rh-python36 rh-git218 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"

**Comment by gefela** [comment]
I can login now
