### ISSUE TITLE
Issues with running the migrate command

### ISSUE THREAD

**Issue by promeathus** [MrMEEE/awx-build#225]
I have attempted the migrate command on both RHEL7 and Centos7 and they both are giving me the same result. I have been unable to find a resolution to get past this point. Any guidance you can give?

I have also been using the minimal install with developer tools. 

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.3.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py", line 11, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

**Comment by techiekannanv** [comment]
As per checking in internet found the python_2_unicode_compatible not part of django.utils.encoding so as suggested in internet installed module six and replaced the entry on file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py like below.
# from django.utils.encoding import python_2_unicode_compatible
from six import python_2_unicode_compatible

Next I got below error 
    from django.utils import six
ImportError: cannot import name 'six'

for updated the python script under /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/jsonfield/

To find other files which is using six from django utils
cd /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/jsonfield/
find . -name \*.py -exec grep -l six {} \;
./fields.py
./forms.py
./utils.py
./widgets.py

Finally stuck at below error and not able to find alternative

  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/consumers.py", line 4, in <module>
    from channels import Group
ImportError: cannot import name 'Group'

**Comment by lharms1** [comment]
I'm having the same issue:
sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.3.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py", line 11, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

**Comment by lharms1** [comment]
Tried an early version of Django "pip3 install Django==1.11.29" still having the issue.

**Comment by MrMEEE** [comment]
Hi guys

Newest version is buggy.. Dependency are not working at the moment.. The upstream project has rebased, and I need to do a lot of work.. I'm pretty sure that I know what to do, but I just haven't got the time right now (house project and Corona situation is taking up a lot of my time)...

I hope to have it fixed within a few weeks.. For now my best recommendation would be to roll back..

**Comment by lharms1** [comment]
No problem, thanks for the update. Hope all goes well on the home front.

**Comment by rafis** [comment]
How to install previous version?

**Comment by lharms1** [comment]
yum check-update ansible-awx
ansible-awx.x86_64             

https://awx.wiki/repository/

**Comment by lharms1** [comment]
I’ve been took  9.2.0 is good.

**Comment by zett93** [comment]
But there is no 9.2.0 release, could You help me with installation that version by rpm?

 yum --showduplicate list ansible-awx shows only 9.3.0 releases

**Comment by zett93** [comment]
i've installed from awx.wiki repo, but still have dep problems - because it gets Django 3.0.4 - @MrMEEE  @lharms1 any ways to fix that? :(

**Comment by MrMEEE** [comment]
@zett93 Sorry.. dependencies are broken right now..

**Comment by zett93** [comment]
@MrMEEE - maybe You have somewhere a list of working deps for older versions?

**Comment by jhquentin** [comment]
I got it working by downgrading some packages
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install Django==2.2.8
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install channels==1.1.8
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install asgiref==1.1.2
sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage makemigrations"
sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
systemctl restart awx

**Comment by zett93** [comment]
OK, I have to do a little bit more, but it works fine now (9.3.0 version :))

`yum install ansible-awx
yum install python-devel
yum groupinstall "Development Tools"
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install Django==2.2.8
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install channels==1.1.8
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install django-split-settings
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install prometheus_client
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install django-qsstats-magic
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install ansiconv
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install python3-memcached
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install schedule
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install attrs==19.2.0
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install asgi_amqp
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install uwsgi
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install radiusauth
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install django-radius
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install tacacs_plus
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install onelogin
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install python3-saml

sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
`

**Comment by lharms1** [comment]
Strange thing is that my buddy in the EU sees the different versions when he connect to the repo(see below):
~]# cat /etc/yum.repos.d/ansible-awx.repo
[copr:copr.fedorainfracloud.org:mrmeee:ansible-awx]
name=Copr repo for ansible-awx owned by mrmeee
baseurl=https://download.copr.fedorainfracloud.org/results/mrmeee/ansible-awx/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/mrmeee/ansible-awx/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1

# yum --showduplicates list ansible-awx
Loaded plugins: enabled_repos_upload, langpacks, package_upload, product-id, search-disabled-repos,
              : subscription-manager
Installed Packages
ansible-awx.x86_64        9.2.0.354-1.el7         @copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
Available Packages
ansible-awx.x86_64        9.3.0.69-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.71-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.73-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.75-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.77-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.79-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.81-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.83-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.86-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.88-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.90-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.92-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.96-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.98-1.el7          copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
ansible-awx.x86_64        9.3.0.104-1.el7         copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
Uploading Enabled Repositories Report
Loaded plugins: langpacks, product-id, subscription-manager


Not exactly sure why.  The EU may be routing to a different server and under different laws/rules mandating retention of older versions where the US does not.

**Comment by MrMEEE** [comment]
@lharms1 yeah, that sounds weird..

If you need older versions, you can get them from here:

https://awx.wiki/repository/

**Comment by pankajps** [comment]
#230

**Comment by bradlyaolson** [comment]
Does anyone else have any downgrading tips? I tried the above, steps by @jhquentin and @zett93 but I get the following error. Thanks in advance!

# sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws = cls()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 648, in __init__
    self.add_entry(entry)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 704, in add_entry
    for dist in find_distributions(entry, True):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2049, in find_on_path
    for dist in factory(fullpath):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2111, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
PermissionError: [Errno 13] Permission denied: '/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/onelogin-1.9.0.dist-info'

**Comment by Nekasas** [comment]
So I used those workarounds which are mentioned by zett93 and jhquentin and everything was working. After some further CentOS upgrade my AWX crashed. 

> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master ws.require(__requires__)
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in requireneeded = self.resolve(parse_requirements(requirements))
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolveraise VersionConflict(dist, req).with_context(dependent_req)pkg_resources.ContextualVersionConflict: (attrs 19.1.0 (/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages), Requirement.par {'Automat'})During handling of the above exception, another exception occurred:Traceback (most recent call last):
File "/opt/rh/rh-python36/root/usr/bin/daphne", line 6, in <module>from pkg_resources import load_entry_point
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>@_call_aside
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_asidef(*args, **kwargs)
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_workinworking_set = WorkingSet._build_master()
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master return cls._build_from_requirements(__requires__)
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements dists = ws.resolve(reqs, Environment())
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve raise VersionConflict(dist, req).with_context(dependent_req) pkg_resources.ContextualVersionConflict: (attrs 19.1.0 (/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages), Requirement.parse('attrs>=19.2.0'), {'Automat'})


How to solve:
/opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install automat==20.2.0

**Comment by zett93** [comment]
@Nekasas in Your last line You have 

> Requirement.parse('attrs>=19.2.0')

Did you try to install that package?

**Comment by Nekasas** [comment]
> @Nekasas in Your last line You have
> 
> > Requirement.parse('attrs>=19.2.0')
> 
> Did you try to install that package?

I couldn't find Automat with 19.2.0, So I installed 20.2.0

**Comment by zett93** [comment]
@Nekasas did You try to install that package from my instructions? Because i don't have installed any package that names "automat"

> /opt/rh/rh-python36/root/usr/bin/python3.6 /opt/rh/rh-python36/root/usr/bin/pip install attrs==19.2.0

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
