### ISSUE TITLE
Daphne service too old

### ISSUE THREAD

**Issue by unrelatedinfo** [MrMEEE/awx-build#226]
So while attempting to install the latest awx-rpm from your repo we are hitting a few issues.

daphne appears to be too old:
```
-- The start-up result is done.
Mar 24 14:54:17 HOSTNAME scl[20243]: Traceback (most recent call last):
Mar 24 14:54:17 HOSTNAME scl[20243]: File "/opt/rh/rh-python36/root/usr/bin/daphne", line 8, in <module>
Mar 24 14:54:17 HOSTNAME scl[20243]: sys.exit(CommandLineInterface.entrypoint())
Mar 24 14:54:17 HOSTNAME scl[20243]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/daphne/cli.py", line 191, in entrypoint
Mar 24 14:54:17 HOSTNAME scl[20243]: cls().run(sys.argv[1:])
Mar 24 14:54:17 HOSTNAME scl[20243]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/daphne/cli.py", line 252, in run
Mar 24 14:54:17 HOSTNAME scl[20243]: application = import_by_path(args.application)
Mar 24 14:54:17 HOSTNAME scl[20243]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/daphne/utils.py", line 12, in import_by_path
Mar 24 14:54:17 HOSTNAME scl[20243]: target = importlib.import_module(module_path)
Mar 24 14:54:17 HOSTNAME scl[20243]: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
Mar 24 14:54:17 HOSTNAME scl[20243]: return _bootstrap._gcd_import(name[level:], package, level)
Mar 24 14:54:17 HOSTNAME scl[20243]: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Mar 24 14:54:17 HOSTNAME scl[20243]: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Mar 24 14:54:17 HOSTNAME scl[20243]: File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
Mar 24 14:54:17 HOSTNAME scl[20243]: File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
Mar 24 14:54:17 HOSTNAME scl[20243]: File "<frozen importlib._bootstrap_external>", line 678, in exec_module
Mar 24 14:54:17 HOSTNAME scl[20243]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Mar 24 14:54:17 HOSTNAME scl[20243]: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/asgi.py", line 12, in <module>
Mar 24 14:54:17 HOSTNAME scl[20243]: from channels.asgi import get_channel_layer
Mar 24 14:54:17 HOSTNAME scl[20243]: ModuleNotFoundError: No module named 'channels.asgi'
Mar 24 14:54:17 HOSTNAME systemd[1]: awx-daphne.service: main process exited, code=exited, status=1/FAILURE
Mar 24 14:54:17 HOSTNAME systemd[1]: Unit awx-daphne.service entered failed state.
Mar 24 14:54:17 HOSTNAME systemd[1]: awx-daphne.service failed.
Mar 24 14:54:19 HOSTNAME systemd[1]: awx-daphne.service holdoff time over, scheduling restart.
Mar 24 14:54:19 HOSTNAME systemd[1]: Stopped AWX daphne service.
```

```
# /opt/rh/rh-python36/root/usr/bin/pip3.6 install asgiref==3.2.5
Requirement already satisfied: asgiref==3.2.5 in ./root/usr/lib/python3.6/site-packages (3.2.5)
```
ERROR: channels 2.4.0 has requirement daphne~=2.3, but you'll have daphne 1.3.0 which is incompatible.

**Comment by dominiquearpin** [comment]
the build is broken... see #225

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
