### ISSUE TITLE
Since 23rd March 2020 - awx installtion is failing 

### ISSUE THREAD

**Issue by pankajps** [MrMEEE/awx-build#227]
-bash-4.2$ echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', '')" | scl enable rh-python36 rh-postgresql10 "awx-manage shell"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.3.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py", line 11, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

---
Seems Python file conflict with rh-python36-gitdb-4.0.2-1.noarch and rh-python36-msgpack packages.

Repository https://copr-be.cloud.fedoraproject.org/results/mrmeee/ansible-awx/epel-7-x86_64/

**Comment by pankajps** [comment]
Import Database data is failing 

sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"


  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py", line 11, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

**Comment by xu001186** [comment]
Experience the same issue

**Comment by xu001186** [comment]
It might works in this way:

Install the python library dependencies without rh-python36-msgpack-python,rh-python36-gitdb  
**_yum -y install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base' -x *-debuginfo,rh-python36-msgpack-python,rh-python36-gitdb rh-python36-*_**

**Comment by pankajps** [comment]
Then the Import Database data is failing

sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29
"GIT_PYTHON_REFRESH=quiet awx-manage migrate"

File
"/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py",
line 11, in
from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

**Comment by gpavinteractiv** [comment]
Same errors seen when trying to upgrade from 9.0.1 to 9.3

**Comment by ekissinger** [comment]
I was about to open the same issue regarding the package conflicts

**Comment by MrMEEE** [comment]
Please refer to my response in https://github.com/MrMEEE/awx-build/issues/225 ... builds are currently broken...

**Comment by Ashjoker24** [comment]
Even I also tried that but i am in same error
![image (2)](https://user-images.githubusercontent.com/43417210/78574303-6faf6c00-7847-11ea-9134-5415e903c911.png)

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
