### ISSUE TITLE
Upgrading to 9.3 problems

### ISSUE THREAD

**Issue by marcosshpak** [MrMEEE/awx-build#230]
Hello, i follow steps on https://awx.wiki/upgrade/standard-upgrade-method
All packages is to update, only these not updated, due to conflicts ...
Package: rh-python36-gitdb V:4.0.2-1
Package: rh-python36-msgpack V:0.6.2-1 

My update is breaking at this point.
[root@awx ~]# sudo -u awx scl enable rh-postgresql10 rh-python36 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.3.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/models.py", line 11, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

**Comment by pankajps** [comment]
This is the same issue as mentioned in #225 , you can follow those steps and can run migrate command

**Comment by MrMEEE** [comment]
**Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/****
