### ISSUE TITLE
awx 11 on RHEL7 virtual environment not found (running inventory script)

### ISSUE THREAD

**Issue by Lobout** [MrMEEE/awx-build#246]
2.532 INFO     Updating inventory 2: Satellite
    3.362 INFO     Reading Ansible inventory source: /tmp/awx_1_9mcnjzrb/foreman.yml
    3.364 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible/
    3.364 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    3.364 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1139, in handle
    raise exc
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1029, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
bwrap: Can't find source path /var/lib/awx/venv/awx: No such file or directory

**Comment by PadiDiver** [comment]
Ditto
AWX 11.2.0
CentOS 7.5.1804
/var/lib/awx/venv/awx   does not exists
/var/lib/awx/venv/ansible -> /var/lib/awx/venv/python3-ansible2.9.7-1152020

**Comment by MrMEEE** [comment]
Can you try to update?

Or just try to put:
ANSIBLE_VENV_PATH = '/var/lib/awx/venv/ansible/'
BASE_VENV_PATH = '/var/lib/awx/venv/ansible/'
CUSTOM_VENV_PATHS = ['/var/lib/awx/venv'

into /etc/tower/settings.py, if they are not there...

**Comment by Lobout** [comment]
This issue seems to be resolved now

**Comment by Lobout** [comment]
issue appears resolved now
