### ISSUE TITLE
ansible inventory modules not working

### ISSUE THREAD

**Issue by Lobout** [MrMEEE/awx-build#251]
awx 11.2 inventory modules fail.  I have confirmed they are working properly with docker version

    2.931 INFO     Updating inventory 2: Satellite
    3.783 INFO     Reading Ansible inventory source: /tmp/awx_2_qm0zf_cj/foreman.yml
    3.785 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible/
    3.785 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    3.785 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1139, in handle
    raise exc
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1029, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.9
  config file = None
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/ansible/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/ansible/bin/ansible-inventory
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
No config file found; using defaults
[WARNING]:  * Failed to parse /tmp/awx_2_qm0zf_cj/foreman.yml with auto plugin:
inventory config '/tmp/awx_2_qm0zf_cj/foreman.yml' specifies unknown plugin
'theforeman.foreman.foreman'
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 53, in parse
    raise AnsibleParserError("inventory config '{0}' specifies unknown plugin '{1}'".format(path, plugin_name))
[WARNING]: Unable to parse /tmp/awx_2_qm0zf_cj/foreman.yml as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by Lobout** [comment]
this looks like a problem with the upstream code #7052  

https://github.com/ansible/awx/issues/7052

**Comment by bamason14** [comment]
It looks like they closed that issue. Is there new code published yet that can be compiled? Was not sure of the build timings in this new repo.

**Comment by Lobout** [comment]
> It looks like they closed that issue. Is there new code published yet that can be compiled? Was not sure of the build timings in this new repo.

I would assume as soon as 11.3 comes out we will see it here, as there are no daily builds going on right now.

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
