### ISSUE TITLE
Inventory script fails on the following:

### ISSUE THREAD

**Issue by crupib** [MrMEEE/awx-build#256]
3.444 INFO     Updating inventory 2: MFS
    4.673 INFO     Reading Ansible inventory source: /tmp/awx_7_eeophsr0/tmpb_rssp6b
    4.675 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible/
    4.675 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    4.675 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/usr/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1139, in handle
    raise exc
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1029, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
bwrap: Can't find source path /var/lib/awx/venv/awx: No such file or directory

**Comment by crupib** [comment]
This was the latest version of AWX. 
 ______________ 
<  AWX 11.2.0  >
 -------------- 
        \   ^__^
         \  (oo)\_______
            (__)      A )\/\
                ||----w |
                ||     ||

**Comment by crupib** [comment]
I got it to work by linking rh-python root inside the venv
