### ISSUE TITLE
error on importing DB data - pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by dbwlsals** [MrMEEE/awx-build#270]
Hi I tried your instruction to install AWX in rhel7 but i am getting ERROR on importing DB data.
I executed the command ' sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate" ' . Please help me to get this fixed. (I have followed this instruction https://awx.wiki/installation/configuration)

**sudo -u awx scl enable rh-python36 rh-postgresql10 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"**
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.3.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 136, in manage
    prepare_env()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 103, in prepare_env
    import oauth2_provider.settings
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/oauth2_provider/__init__.py", line 4, in <module>
    __version__ = pkg_resources.require("django-oauth-toolkit")[0].version
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sqlparse>=0.2.2' distribution was not found and is required by django

**Comment by MrMEEE** [comment]
Hi.. please look at the new installation guide...

https://awx.wiki/blog/new-build-server-new-installer-new-maintainers-same-project

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
