### ISSUE TITLE
RH7 - Upgrade from AWX 9.3 to 11

### ISSUE THREAD

**Issue by psmola** [MrMEEE/awx-build#272]
Hi,
Today I upgraded AWX instance from version 9.3.0.104-1 on RedHat 7 to 11.2.0-20.1. All  packages from repository have been installed. Also awx-manage makemigrations and awx-manage migrate finished without errors.
I started application but in logs I see error:
systemd: Started AWX channels worker service.
scl: Traceback (most recent call last):
scl: File "/opt/rh/rh-python36/root/usr/bin/daphne", line 11, in <module>
scl: load_entry_point('daphne==1.3.0', 'console_scripts', 'daphne')()
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/daphne/cli.py", line 144, in entrypoint
scl: cls().run(sys.argv[1:])
scl: File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/daphne/cli.py", line 174, in run
scl: channel_layer = importlib.import_module(module_path)
scl: File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
scl: return _bootstrap._gcd_import(name[level:], package, level)
scl: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
scl: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
scl: File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
scl: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
scl: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
scl: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
scl: File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
scl: ModuleNotFoundError: No module named 'awx'
systemd: awx-daphne.service: main process exited, code=exited, status=1/FAILURE
systemd: Unit awx-daphne.service entered failed state.
systemd: awx-daphne.service failed.

It looks that has a problem with loading "awx" module.

Regards

**Comment by psmola** [comment]
Hi 
I reproduce upgrade from 9.2 to 11. Below are all steps what I did :
```
yum versionlock delete ansible-awx

systemctl stop awx
yum -y -q install policycoreutils-python
yum -y -q install redis
yum -y -q install ansible-awx
#  /etc/tower/settings.py saved as /etc/tower/settings.py.rpmsave

cp /etc/tower/settings.py.rpmsave /etc/tower/settings.py
sudo -u awx scl enable rh-postgresql10 "GIT_PYTHON_REFRESH=quiet awx-manage migrate"
awx-create-venv -f
# Replace values in /etc/tower/settings.py to new enviroment
ANSIBLE_VENV_PATH = '/var/lib/awx/venv/ansible/'
BASE_VENV_PATH = '/var/lib/awx/venv/ansible/'
CUSTOM_VENV_PATHS = ['/var/lib/awx/venv']

ln -s  /usr/bin/virtualenv-3 /usr/bin/virtualenv
```
I removed rabbitmq configuration  and CHANNEL_LAYERS from settings.py

and upgrade is done. 
**I may confirm that  upgrade from AWX 9.2 to AWX 11 has been successfully done.**

**Comment by psmola** [comment]
Upgrade from version 9.2 to 11 done.

**Comment by psmola** [comment]
https://github.com/psmola/awx_patching - ansible patching role from AWX 9.2 to version 11.2
