### ISSUE TITLE
AWX error (ModuleNotFoundError: No module named 'asgiref')

### ISSUE THREAD

**Issue by nimishchandra32908** [MrMEEE/awx-build#277]
Hello Team,
i am trying to install AWX on centos 7 but some how i am getting below error please help me to resolve this issue.

([root@ip-172-31-46-99 bin]# sudo -u awx scl enable rh-python36 rh-postgresql10 "/opt/rh/rh-python36/root/usr/bin/awx-man
age migrate"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.3.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 32, in <module>
    from django.db.backends.base import schema
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/__init__.py", line 2, in <module>
    from django.db.utils import (
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/utils.py", line 5, in <module>
    from asgiref.local import Local
ModuleNotFoundError: No module named 'asgiref' )

I am following the installations steps form https://awx.wiki/installation/configuration 

Please help me asap.

Thanks
ND

**Comment by Rthur** [comment]
Without knowing your build-specs, I can recreate the error on the following platform.

```Linux 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

The cause of your issue is the failure to install rh-python36* from mrmee-ansible-awx failed.

If you recursively install one package at a time, you will see that two packages are actually giving you issues:

```for p in $(yum list --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo rh-python36* | awk '/mrmeee/ { print $1 }');do yum -y install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' ${p};done```

These are the two packages that are causing issues.

* rh-python36-gitdb2
* rh-python36-msgpack-python

As such, you have not successfully install ansible-awx either.

**Comment by Rthur** [comment]
```
# yum -y --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' install rh-python36-gitdb2
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftpmirror.your.org
Resolving Dependencies
--> Running transaction check
---> Package rh-python36-gitdb2.noarch 0:2.0.6-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================================================================================================================================================================
 Package                                                 Arch                                        Version                                        Repository                                               Size
==================================================================================================================================================================================================================
Installing:
 rh-python36-gitdb2                                      noarch                                      2.0.6-1                                        mrmeee-ansible-awx                                      104 k

Transaction Summary
==================================================================================================================================================================================================================
Install  1 Package

Total size: 104 k
Installed size: 454 k
Downloading packages:
Running transaction check
Running transaction test


Transaction check error:
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__init__.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__init__.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__init__.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/__init__.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/base.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/base.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/base.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/base.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/const.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/const.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/exc.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/exc.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/fun.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/fun.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/pack.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/pack.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/pack.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/pack.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/stream.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/stream.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/typ.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/typ.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/util.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/__pycache__/util.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/base.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/base.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/const.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/git.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/git.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/loose.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/loose.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/mem.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/mem.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/ref.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/__pycache__/ref.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/git.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/loose.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/mem.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/pack.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/pack.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/db/ref.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/exc.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/fun.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/stream.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/lib.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/lib.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_base.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_base.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_example.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_example.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_pack.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_pack.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_stream.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_stream.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_util.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/__pycache__/test_util.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/lib.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_base.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_example.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_pack.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_stream.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/test/test_util.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/typ.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/util.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/encoding.cpython-36.opt-1.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/__pycache__/encoding.cpython-36.pyc from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch
  file /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/gitdb/utils/encoding.py from install of rh-python36-gitdb2-2.0.6-1.noarch conflicts with file from package rh-python36-gitdb-4.0.2-1.noarch

Error Summary
-------------
```

**Comment by Rthur** [comment]
```
# yum -y --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' install --show-duplicates rh-python36-msgpack-python
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.cs.vt.edu
Resolving Dependencies
--> Running transaction check
---> Package rh-python36-msgpack-python.x86_64 0:0.5.6-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================================================================================================================================================================
 Package                                                       Arch                                      Version                                      Repository                                             Size
==================================================================================================================================================================================================================
Installing:
 rh-python36-msgpack-python                                    x86_64                                    0.5.6-1                                      mrmeee-ansible-awx                                     89 k

Transaction Summary
==================================================================================================================================================================================================================
Install  1 Package

Total size: 89 k
Installed size: 291 k
Downloading packages:
Running transaction check
Running transaction test


Transaction check error:
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__init__.py from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/__init__.cpython-36.opt-1.pyc from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/__init__.cpython-36.pyc from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/_version.cpython-36.opt-1.pyc from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/_version.cpython-36.pyc from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/exceptions.cpython-36.opt-1.pyc from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/exceptions.cpython-36.pyc from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/fallback.cpython-36.opt-1.pyc from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/__pycache__/fallback.cpython-36.pyc from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/_version.py from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/exceptions.py from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64
  file /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/msgpack/fallback.py from install of rh-python36-msgpack-python-0.5.6-1.x86_64 conflicts with file from package rh-python36-msgpack-0.6.2-1.x86_64

Error Summary
-------------
```

**Comment by Rthur** [comment]
Erase the follow packages
```
yum -y install --disablerepo='*' --enablerepo='mrmeee-ansible-awx, base' -x *-debuginfo -x rh-python36-msgpack-0.6.2-1.x86_64 -x rh-python36-gitdb-4.0.2-1.noarch rh-python36*
```

**Comment by albebert** [comment]
same here, and nothing work :/ any help ?

**Comment by MrMEEE** [comment]
Project has been updated and moved...

Please move to the new version and report any issues

PROJECT MOVED: https://github.com/miracle-as/AWX-RPM

Issues at: https://github.com/miracle-as/AWX-RPM/issues

**Install guide, tools, utilities are located at: https://awx.wiki

**LinkedIn group for Questions, support, talk and more: https://www.linkedin.com/groups/13694893/**
