### ISSUE TITLE
rpmbuild: ImportError: cannot import name requests

### ISSUE THREAD

**Issue by flynn1973** [MrMEEE/awx-build#34]
while trying to do a local build with your latest source rpm the follwing comes up. any hint what might
be the problem here?

````
packagebuilder@lpgaixmgmtlx01:/home/packagebuilder/rpmbuild/SPECS>rpmbuild -ba awx-build.spec
warning: bogus date in %changelog: Thu Nov 21 2017 18:14:55 +0300 Matvey Kruglov <kubuzzzz@gmail.com> 1.0.1.225-1
warning: bogus date in %changelog: Wed Sep 21 2017 14:44:23 +0300 Matvey Kruglov <kubuzzzz@gmail.com> 1.0.0.505-1
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.GOKk2o
+ umask 022
+ cd /home/packagebuilder/rpmbuild/BUILD
+ cd /home/packagebuilder/rpmbuild/BUILD
+ rm -rf awx-1.0.6.43
+ /usr/bin/tar -xf -
+ /usr/bin/gzip -dc /home/packagebuilder/rpmbuild/SOURCES/awx-1.0.6.43.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd awx-1.0.6.43
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.DB1AqQ
+ umask 022
+ cd /home/packagebuilder/rpmbuild/BUILD
+ cd awx-1.0.6.43
+ virtualenv _buildenv/
New python executable in /home/packagebuilder/rpmbuild/BUILD/awx-1.0.6.43/_buildenv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/packagebuilder..._buildenv/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/usr/lib64/python2.7/pkgutil.py", line 581, in get_data
    mod = sys.modules.get(package) or loader.load_module(package)
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 83, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 42, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/cmdoptions.py", line 16, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/index.py", line 15, in <module>
ImportError: cannot import name requests
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/packagebuilder..._buildenv/bin/python - setuptools pip wheel failed with error code 1
error: Bad exit status from /var/tmp/rpm-tmp.DB1AqQ (%build)


RPM build errors:
    bogus date in %changelog: Thu Nov 21 2017 18:14:55 +0300 Matvey Kruglov <kubuzzzz@gmail.com> 1.0.1.225-1
    bogus date in %changelog: Wed Sep 21 2017 14:44:23 +0300 Matvey Kruglov <kubuzzzz@gmail.com> 1.0.0.505-1
    Bad exit status from /var/tmp/rpm-tmp.DB1AqQ (%build)
````

**Comment by flynn1973** [comment]
fixed by removing the "pip-10.0.1-py2.py3-none-any.whl" wheel. not sure whats up with this. can be closed as "local problem".
