### ISSUE TITLE
1.0.7.3 clean install:  ImportError: No module named rest_framework_swagger

### ISSUE THREAD

**Issue by flynn1973** [MrMEEE/awx-build#43]
something seems to be missing in the embedded python stuff.
pip install  django-rest-swagger fixed it but i'm not shure if this is the right way to do.

````
sudo -u awx /opt/awx/bin/awx-manage migrate
Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 116, in manage
    execute_from_command_line(sys.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named rest_framework_swagger
````

**Comment by flynn1973** [comment]
works with 1.0.7.4, so i will close this issue.
