### ISSUE TITLE
sqlite3.InterfaceError

### ISSUE THREAD

**Issue by franysk** [MrMEEE/awx-build#50]
Help please, which day I struggle with the problem, I can not install awx by link https://github.com/MrMEEE/awx-build/blob/master/installguide.md

**sudo -u awx /opt/awx/bin/awx-manage migrate**
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, djcelery, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  Applying main.0006_v320_release...Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/usr/lib/python2.7/site-packages/awx-2.0.1-py2.7.egg/awx/__init__.py", line 116, in manage
    execute_from_command_line(sys.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/operations/special.py", line 108, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/operations/special.py", line 129, in _run_sql
    schema_editor.execute(sql, params=params)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/backends/utils.py", line 83, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/backends/sqlite3/operations.py", line 135, in last_executed_query
    params = self._quote_params_for_last_executed_query(params)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/backends/sqlite3/operations.py", line 124, in _quote_params_for_last_executed_query
    return cursor.execute(sql, params).fetchone()
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

**Comment by MrMEEE** [comment]
Are you trying to setup awx with sqlite? Haven't tried that..

**Comment by franysk** [comment]
I wrote a command from the manual
Probably, an error occurs in the function:
    def _quote_params_for_last_executed_query(self, params):
        """
        Only for last_executed_query! Don't use this to execute SQL queries!
        """
        # This function is limited both by SQLITE_LIMIT_VARIABLE_NUMBER (the
        # number of parameters, default = 999) and SQLITE_MAX_COLUMN (the
        # number of return values, default = 2000). Since Python's sqlite3
        # module doesn't expose the get_limit() C API, assume the default
        # limits are in effect and split the work in batches if needed.
        BATCH_SIZE = 999
        if len(params) > BATCH_SIZE:
            results = ()
            for index in range(0, len(params), BATCH_SIZE):
                chunk = params[index:index + BATCH_SIZE]
                results += self._quote_params_for_last_executed_query(chunk)
            return results

        sql = 'SELECT ' + ', '.join(['QUOTE(?)'] * len(params))
        # Bypass Django's wrappers and use the underlying sqlite3 connection
        # to avoid logging this query - it would trigger infinite recursion.
        cursor = self.connection.connection.cursor()
        # Native sqlite3 cursors cannot be used as context managers.
        try:
            return cursor.execute(sql, params).fetchone()
        finally:
            cursor.close()


Can I get postgres to be used?

**Comment by MrMEEE** [comment]
If you follow the complete install instruction, then it will be installer with postgres.. Have you done all of the steps?

**Comment by franysk** [comment]
I am using postgress 10 version.
The rest is according to the manual

**Comment by MrMEEE** [comment]
There is probably your problem.. haven't tested with postgres 10.. Should work, but apparently need some work..

**Comment by MrMEEE** [comment]
Postgresql 10 is supported/required from awx-rpm 3.0.0..
