### ISSUE TITLE
Unable to import playbook from SVN

### ISSUE THREAD

**Issue by jijendiranR** [MrMEEE/awx-build#56]
While importing playbook from SCM(subversion) getting this below error

Traceback (most recent call last): File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/tasks.py", line 930, in run self.pre_run_hook(instance, **kwargs)
File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/tasks.py", line 1749,in pre_run_hook self.acquire_lock(instance) 
File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/tasks.py", line 1717, in acquire_lock self.lock_fd = os.open(lock_path, os.O_RDONLY | os.O_CREAT) 
OSError: [Errno 13] Permission denied: '/etc/ansible/_4__demo_project.lock'

Suggest a solution to fix it.
NOTE:/etc/ansible/  is in awx permission only

**Comment by MrMEEE** [comment]
Hmmm.. New installation?? Has it worked before??

Are you running with SELinux active??

**Comment by jijendiranR** [comment]
It is a new installation. Trying to import playbook from svn.
SELinux is in the enabled state.

**Comment by MrMEEE** [comment]
Ok.. Might be SELinux enabled, haven't been tested throughly yet..

Can you try to temporarily disable SELinux (setenforce 0)?? And try to import again

**Comment by jijendiranR** [comment]
Tried by setenforce 0 disabled SELinux again facing the above-mentioned error.

**Comment by MrMEEE** [comment]
Which version of AWX are you on??

**Comment by jijendiranR** [comment]
AWX Version 2.1.0

**Comment by MrMEEE** [comment]
From the awx or awx-dev repo??

Can you run a 

rpm -aq awx

**Comment by jijendiranR** [comment]
This is the awx version I have installed
awx-2.1.0.131-1.el7.x86_64

**Comment by MrMEEE** [comment]
Haven't tried with subversion..

Could you verify that git works?

**Comment by jijendiranR** [comment]
Traceback (most recent call last): File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/tasks.py", line 930, in run self.pre_run_hook(instance, **kwargs) File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/tasks.py", line 1749, in pre_run_hook self.acquire_lock(instance) File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/tasks.py", line 1717, in acquire_lock self.lock_fd = os.open(lock_path, os.O_RDONLY | os.O_CREAT) OSError: [Errno 13] Permission denied: '/etc/ansible/_29__git.lock'

Getting the above error while  GIT integration

**Comment by MrMEEE** [comment]
Have just installed a fresh new awx-2.1.0.241-1.el7.x86_64 here.. following the install guide step by step.. and it works..

Any custom steps?

**Comment by MrMEEE** [comment]
Please reopen if this problem persists
