### ISSUE TITLE
Error - awx-manage inventory_import 

### ISSUE THREAD

**Issue by Rpera** [MrMEEE/awx-build#7]
Hello, Sorry if here is not the right place for this. But i'm having a issue with the build: 1.0.4.98-1.el7.centos

I can't import any inventories into awx instance. Is this already being handle?

Output command line:
[root@towerawx ruipereira]# awx-manage inventory_import --source=/var/lib/awx/projects/ruipereira/inventories/Net_80/hosts --inventory-name="80" --overwrite --overwrite-vars
Traceback (most recent call last):
  File "/bin/awx-manage", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
**pkg_resources.DistributionNotFound: awx==3.2.1
![awx-gui_importing_inventory](https://user-images.githubusercontent.com/26353235/37533993-6718ad8e-293b-11e8-9dec-dffac319d24c.png)
**

Attached is one picture from web interface trying to import the same inventory.

Thank-you
Best Regards
Rui Pereira

**Comment by MrMEEE** [comment]
hi..

try:
sudo -u awx /opt/awx/bin/awx-manage {rest of your arguments)

**Comment by Rpera** [comment]
Hello MRMEEE,

Sorry for the late feedback but i've updated to teh latest build and I still gto this error when i tried to update an inventory:

[root@towerawx tofh]# sudo -u awx /opt/awx/bin/awx-manage inventory_import --source=/var/lib/awx/projects/ruipereira/inventories/Net_80/hosts --inventory-name="81net" --overwrite --overwrite-vars
2018-03-26 17:01:04,253 INFO     awx.main.commands.inventory_import Updating inventory 2: 81net
2018-03-26 17:01:04,606 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /var/lib/awx/projects/ruipereira/inventories/Net_80/hosts
Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 993, in handle
    self.is_custom)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source
    is_custom=is_custom).load()
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 177, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 160, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=250) with stdout:
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible-inventory", line 97, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/cli/__init__.py", line 38, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/inventory/manager.py", line 33, in <module>
    from ansible.plugins.loader import PluginLoader
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/plugins/loader.py", line 22, in <module>
    from ansible.parsing.plugin_docs import read_docstring
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/parsing/plugin_docs.py", line 12, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/parsing/yaml/loader.py", line 30, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/parsing/yaml/constructor.py", line 29, in <module>
    from ansible.parsing.vault import VaultLib
  File "/opt/awx/embedded/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 45, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/opt/awx/embedded/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/opt/awx/embedded/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/opt/awx/embedded/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/awx/embedded/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/opt/awx/embedded/lib/python2.7/site-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/awx/embedded/lib/python2.7/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'bcrypt>=3.1.3' distribution was not found and is required by paramiko

stderr:
ERROR! Unexpected Exception, this is probably a bug: The 'bcrypt>=3.1.3' distribution was not found and is required by paramiko

Can you point me in the right direction?? Do you have a list of all dependencies that need to be installed on the machine before install awx?

Thank-you in advance
Best Regards
RP

**Comment by MrMEEE** [comment]
Hi

Could you send me your inventory script?

**Comment by Rpera** [comment]
Hi,

Sure you want my hosts file? or what do you mean by inventory script?

I've attached my hosts file.

Thank-you in advance for your support
Best Regards
Rui Pereira
[hosts.txt](https://github.com/MrMEEE/awx-build/files/1851462/hosts.txt)

**Comment by MrMEEE** [comment]
Works perfectly here:

[root@akiva ~]# sudo -u awx /opt/awx/bin/awx-manage inventory_import --source=/tmp/hosts --inventory-name="test" --overwrite --overwrite-vars
2018-03-27 10:11:51,248 INFO     awx.main.commands.inventory_import Updating inventory 3: test
2018-03-27 10:11:51,293 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /tmp/hosts
2018-03-27 10:11:52,047 INFO     awx.main.commands.inventory_import Processing JSON output...
2018-03-27 10:11:52,047 INFO     awx.main.commands.inventory_import Loaded 6 groups, 5 hosts
2018-03-27 10:11:52,058 INFO     awx.main.commands.inventory_import Inventory variables unmodified
2018-03-27 10:11:52,063 INFO     awx.main.commands.inventory_import Group "linux_servers" added
2018-03-27 10:11:52,066 INFO     awx.main.commands.inventory_import Group "linux_std_servers" added
2018-03-27 10:11:52,069 INFO     awx.main.commands.inventory_import Group "monitoring_servers" added
2018-03-27 10:11:52,072 INFO     awx.main.commands.inventory_import Group "prime_servers" added
2018-03-27 10:11:52,074 INFO     awx.main.commands.inventory_import Group "win_servers" added
2018-03-27 10:11:52,077 INFO     awx.main.commands.inventory_import Group "win_std_servers" added
2018-03-27 10:11:52,086 INFO     awx.main.commands.inventory_import Host "80fwgui" added
2018-03-27 10:11:52,089 INFO     awx.main.commands.inventory_import Host "80rhel1" added
2018-03-27 10:11:52,091 INFO     awx.main.commands.inventory_import Host "80test" added
2018-03-27 10:11:52,094 INFO     awx.main.commands.inventory_import Host "80test1" added
2018-03-27 10:11:52,097 INFO     awx.main.commands.inventory_import Host "monitoringsrv" added
2018-03-27 10:11:52,105 INFO     awx.main.commands.inventory_import Group "monitoring_servers" added as child of "linux_servers"
2018-03-27 10:11:52,111 INFO     awx.main.commands.inventory_import Group "win_std_servers" added as child of "win_servers"
2018-03-27 10:11:52,119 INFO     awx.main.commands.inventory_import Host "80rhel1" added to group "linux_std_servers"
2018-03-27 10:11:52,125 INFO     awx.main.commands.inventory_import Host "monitoringsrv" added to group "monitoring_servers"
2018-03-27 10:11:52,130 INFO     awx.main.commands.inventory_import Host "80test" added to group "prime_servers"
2018-03-27 10:11:52,131 INFO     awx.main.commands.inventory_import Host "80test1" added to group "prime_servers"
2018-03-27 10:11:52,136 INFO     awx.main.commands.inventory_import Host "80fwgui" added to group "win_std_servers"
2018-03-27 10:11:52,137 DEBUG    awx.main.models.inventory Going to update inventory computed fields
2018-03-27 10:11:52,213 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
2018-03-27 10:11:52,213 INFO     awx.main.commands.inventory_import Inventory import completed for  (test - 18) in 1.0s


When did you last update??? which version are you running???

**Comment by Rpera** [comment]
Hi,

I've updated last night awx to the following version:

[tofh@towerawx ~]$ sudo yum list awx
[sudo] password for tofh:
Installed Packages
awx.x86_64                                                        1.0.5.3-1.el7.centos                                                        @mrmeee-awx-dev

**Comment by MrMEEE** [comment]
Did you remember to run the database migrations???

**Comment by Rpera** [comment]
Yes I run database migration and i didn't have any errors.
Do you think if i install a new machine from scratch this problem disappear?

**Comment by MrMEEE** [comment]
Don't know, but it works here?... you could also try to do a:

yum remove awx
rm -rf /opt/awx
yum install awx

**Comment by Rpera** [comment]
Ok, I will give it another try and let you know how it ended.

Best Regards
Rui Pereira

**Comment by MrMEEE** [comment]
cool :)

**Comment by Rpera** [comment]
Just to let you know that i've manage to import the inventory from the command line but from the AWX GUI i still have the same error. (see initial post from me).
However i found now that from AWX GUI we don't have information for the output jobs.
![awx_error](https://user-images.githubusercontent.com/26353235/37977178-2ca7512a-31db-11e8-9863-a51302bade10.png)

Do you have this situation as well? 

Do you know when we will have a stable build with ansible 2.4 ? I'm currently installing the builds from the dev branch because i need ansible 2.4.x.x running in the background. 

thank-you for your support

Best Regards
Rui Pereira

**Comment by MrMEEE** [comment]
How exactly do you configure awx to use the hosts file???
Please show me a screenshot from the "Inventory Scripts" page, that you use?

I have kind of dropped the stable build branch, since it seems that there are no stable builds comming from the AWX people.. thought they would have some stable releases, but as far as I can see, it's just running with the devel-branch.. But I will try to look into it again...

**Comment by MrMEEE** [comment]
BTW. I get the same error as you, if I use a script that doesn't return valid json...

**Comment by Rpera** [comment]
Just to sum up: 
- From AWX GUI i can't import any inventory via source. It gives me the error that i've posted here (1st post from me)
- From command line i was able to import the hosts files via the command that i already show you:
sudo -u awx /opt/awx/bin/awx-manage inventory_import --source=/var/lib/awx/projects/ruipereira/inventories/Net_81/hosts --inventory-name="Net_81"

The problem now is that I don't have any logs from the jobs. (any job, project synchronization, template running..etc)
I've attached some prints from the inventory page.
[awx_inventories.pdf](https://github.com/MrMEEE/awx-build/files/1855448/awx_inventories.pdf)

Thank-you

**Comment by MrMEEE** [comment]
What do you have in the "Sources" tab under inventories???

Which inventory scripts do you have under "Inventory Scripts"????

**Comment by Rpera** [comment]
under sources: 
![image](https://user-images.githubusercontent.com/26353235/38029343-7edfcd16-328d-11e8-8350-b793ad7e73d4.png)

I don't have any inventory Scripts. 
![image](https://user-images.githubusercontent.com/26353235/38029621-3bd69f9e-328e-11e8-85a0-3a651f3f1c79.png)

Why do i need this? I sync the project via GIT to the AWX and then run a cronjob script that imports in to awx the inventories that i want via something like this:

sudo -u awx /opt/awx/bin/awx-manage inventory_import --source=/var/lib/awx/projects/ruipereira/inventories/Net_81/hosts --inventory-name="Net_81"

Do i need anything else?

**Comment by MrMEEE** [comment]
Sry.. thought you were doing scripts...

I have the same error as you, but I have found another way... 

If you add a source, type "Sourced from a project", and then choose the git repo that you have the inventory in.. then you can choose the file, and a least here, it imports correctly.. The job still looks weird, but it works...

**Comment by Rpera** [comment]
Hum..I think this is not yet in a phase that we can work on a daily basis with the tool. (unfortunately )

AWX without the log feature fully working, for me don't make much sense..In this the case i rather work directly with ansible core. 

I will wait a couple of weeks, and then, I will comeback to this again. Maybe in a most-up-to-date version of awx build all of these problems are gone.

Thank-you for your help
Best Regards
Rui Pereira

**Comment by MrMEEE** [comment]
Can you try to do a: 

chmod 744 -R /opt/awx/embedded

Logs works here now..

**Comment by Rpera** [comment]
Hi,

Thank-you for the tip!! It's works also from here! 
I will test it more, but at least now, I think i'm able to run some playbooks.

Best Regards
R&P

**Comment by MrMEEE** [comment]
Great.. thanks for the feedback
