### ISSUE TITLE
errors importing inventory: Permission denied

### ISSUE THREAD

**Issue by chuegel** [MrMEEE/awx-build#8]
I cannot import any inventories. The job fails with:

```
2018-03-18 22:51:32,060 INFO     awx.main.commands.inventory_import Updating inventory 2: lxd inevntory
2018-03-18 22:51:32,080 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /var/lib/awx/projects/_6__ansible_awx/inventory/hosts
Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 993, in handle
    self.is_custom)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source
    is_custom=is_custom).load()
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 177, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 153, in command_to_json
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

```
Any help is much appreciated.

**Comment by chuegel** [comment]
There where permissions missing on `/opt/awx/embedded`

`chmod 744 -R /opt/awx/embedded` fixed the issue

**Comment by MrMEEE** [comment]
Hi

In which version did you encounter this?? I think I fixed this a while back

**Comment by MrMEEE** [comment]
but thanks for the feedback

**Comment by chuegel** [comment]
I used this repo `wget -O /etc/yum.repos.d/awx-rpm.repo https://copr.fedorainfracloud.org/coprs/mrmeee/awx-dev/repo/epel-7/mrmeee-awx-dev-epel-7.repo
`4 days ago.

**Comment by MrMEEE** [comment]
hmm... weird.. thanks for the feedback
