### ISSUE TITLE
Upgrading from 2.1.0 to 3.0.1 broke everything

### ISSUE THREAD

**Issue by angystardust** [MrMEEE/awx-build#82]
Since I've upgraded to 3.0.1 nothing seems to work anymore
I suppose it has something to do with the new ANSIBLE_VENV_PATH (/opt/rh/rh-python36/root/)

I've already tried to restart all the services but I still have errors running nearly everything

```
    2.734 INFO     Updating inventory 3: vmware-test
    2.751 INFO     Reading Ansible inventory source: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
    2.753 INFO     Using VIRTUAL_ENV: /opt/rh/rh-python36/root/
    2.753 INFO     Using PATH: /opt/rh/rh-python36/root/bin:/var/lib/awx/venv/awx/bin:/opt/rh/rh-postgresql10/root/usr/bin:/opt/rh/rh-python36/root/usr/bin:/opt/awx/bin:/bin:/sbin:/usr/bin:/usr/sbin
    2.753 INFO     Using PYTHONPATH: /opt/rh/rh-python36/root/lib/python3.6/site-packages:
    6.132 ERROR    ansible-inventory failed (rc=1) with stdout:

stderr:
 [WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
Traceback (most recent call last):   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 772, in <module>
print(VMWareInventory().show())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 145, in __init__
self.do_api_calls_update_cache()   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 184, in
do_api_calls_update_cache     self.inventory =
self.instances_to_inventory(self.get_instances())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 351, in get_instances
return self._get_instances(kwargs)   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 393, in
_get_instances     for instance in sorted(instances): TypeError: '<' not
supported between instances of 'vim.VirtualMachine' and 'vim.VirtualMachine'

 [WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source

ERROR! No inventory was parsed, please check your configuration and options.

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1111, in handle
    raise exc
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1003, in handle
    data = AnsibleInventoryLoader(source=source, is_custom=self.is_custom, venv_path=venv_path).load()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 195, in load
    return self.command_to_json(base_args + ['--list'])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 178, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:

stderr:
 [WARNING]:  * Failed to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
Traceback (most recent call last):   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 772, in <module>
print(VMWareInventory().show())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 145, in __init__
self.do_api_calls_update_cache()   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 184, in
do_api_calls_update_cache     self.inventory =
self.instances_to_inventory(self.get_instances())   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 351, in get_instances
return self._get_instances(kwargs)   File "/opt/rh/rh-
python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 393, in
_get_instances     for instance in sorted(instances): TypeError: '<' not
supported between instances of 'vim.VirtualMachine' and 'vim.VirtualMachine'

 [WARNING]: Unable to parse /opt/rh/rh-python36/root/usr/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source

ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by MrMEEE** [comment]
My initial thought is that your investors script is not python3 compatible.. Have you tried testing it with python3..

If that IS the case, and you don't wanna spend time updating it to python3, you can create a python2 venv.. Even though AWX is updated to python3 itself, it still supports python2 venvs

**Comment by angystardust** [comment]
I'm using the embedded `vmware_inventory.py` contained in the rpm packages. In 2.1 it worked but now it's working anymore. I'll try to create a python27 venv ;)

**Comment by MrMEEE** [comment]
Did you get it to work?

**Comment by MrMEEE** [comment]
Please reopen, if this issue persists
