### ISSUE TITLE
Template job is failing with 500 internal server error

### ISSUE THREAD

**Issue by murali741** [MrMEEE/awx-build#84]
Hi Martin,

I have installed AWX as the instructions listed. Everything looks good but I have created job template and trying to run the job but I am getting error: Call to /api/v2/job_templates/7/launch failed. POST returned status: 500. A server error has occurred.

What is the fix for this error ??

Thanks
Murali Medi

**Comment by MrMEEE** [comment]
Hi

Can you please look in the logs in /var/log/tower, and paste the errors?

**Comment by murali741** [comment]
[pid: 9339|app: 0|req: 1/1] 192.168.153.1 () {44 vars in 2307 bytes} [Mon Mar 11 22:18:36 2019] GET / => generated 11337 bytes in 721 msecs (HTTP/1.1 200) 7 headers in 320 bytes (1 switches on core 0)
[pid: 9345|app: 0|req: 1/2] 192.168.153.1 () {44 vars in 2280 bytes} [Mon Mar 11 22:18:37 2019] GET /api/ => generated 173 bytes in 1536 msecs (HTTP/1.1 200) 11 headers in 479 bytes (1 switches on core 0)
[pid: 9345|app: 0|req: 2/3] 192.168.153.1 () {46 vars in 2302 bytes} [Mon Mar 11 22:18:39 2019] GET /api/ => generated 173 bytes in 182 msecs (HTTP/1.1 200) 11 headers in 479 bytes (1 switches on core 0)
[pid: 9341|app: 0|req: 1/4] 192.168.153.1 () {46 vars in 2378 bytes} [Mon Mar 11 22:18:38 2019] OPTIONS /api/v2/workflow_job_templates/ => generated 11862 bytes in 1504 msecs (HTTP/1.1 200) 10 headers in 390 bytes (1 switches on core 0)
[pid: 9337|app: 0|req: 1/5] 192.168.153.1 () {46 vars in 2360 bytes} [Mon Mar 11 22:18:38 2019] OPTIONS /api/v2/job_templates/ => generated 21708 bytes in 1600 msecs (HTTP/1.1 200) 10 headers in 390 bytes (1 switches on core 0)
[pid: 9345|app: 0|req: 3/6] 192.168.153.1 () {46 vars in 2308 bytes} [Mon Mar 11 22:18:39 2019] GET /api/v2/ => generated 1545 bytes in 182 msecs (HTTP/1.1 200) 10 headers in 383 bytes (1 switches on core 0)
[pid: 9340|app: 0|req: 1/7] 192.168.153.1 () {44 vars in 2463 bytes} [Mon Mar 11 22:18:38 2019] GET /api/v2/unified_job_templates/?page_size=20&order_by=name&type=workflow_job_template,job_template => generated 6503 bytes in 2944 msecs (HTTP/1.1 200) 10 headers in 383 bytes (1 switches on core 0)
[pid: 9339|app: 0|req: 2/8] 192.168.153.1 () {44 vars in 2300 bytes} [Mon Mar 11 22:18:39 2019] GET /api/v2/config/ => generated 700 bytes in 2187 msecs (HTTP/1.1 200) 10 headers in 396 bytes (1 switches on core 0)
[pid: 9345|app: 0|req: 4/9] 192.168.153.1 () {44 vars in 2300 bytes} [Mon Mar 11 22:18:41 2019] GET /api/v2/config/ => generated 700 bytes in 62 msecs (HTTP/1.1 200) 10 headers in 396 bytes (1 switches on core 0)
[pid: 9337|app: 0|req: 2/10] 192.168.153.1 () {50 vars in 2470 bytes} [Mon Mar 11 22:18:41 2019] OPTIONS /api/v2/unified_job_templates/ => generated 9113 bytes in 106 msecs (HTTP/1.1 200) 10 headers in 383 bytes (1 switches on core 0)
[pid: 9340|app: 0|req: 2/11] 192.168.153.1 () {44 vars in 2332 bytes} [Mon Mar 11 22:18:43 2019] GET /api/v2/job_templates/7/launch/ => generated 786 bytes in 301 msecs (HTTP/1.1 200) 10 headers in 388 bytes (1 switches on core 0)
[pid: 9337|app: 0|req: 3/12] 192.168.153.1 () {46 vars in 2378 bytes} [Mon Mar 11 22:18:43 2019] OPTIONS /api/v2/job_templates/7/launch/ => generated 5533 bytes in 331 msecs (HTTP/1.1 200) 10 headers in 389 bytes (1 switches on core 0)
2019-03-11 22:18:43,644 ERROR    django.request Internal Server Error: /api/v2/job_templates/7/launch/
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/wsgi.py", line 72, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/api/generics.py", line 334, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/api/views/__init__.py", line 2367, in post
    new_job = obj.create_unified_job(**serializer.validated_data)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/jobs.py", line 348, in create_unified_job
    job = super(JobTemplate, self).create_unified_job(**kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 384, in create_unified_job
    unified_job.save()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 839, in save
    result = super(UnifiedJob, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/polymorphic/models.py", line 83, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/base.py", line 198, in save
    super(PasswordFieldsModel, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/base.py", line 316, in save
    super(PrimordialModel, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/base.py", line 164, in save
    super(CreatedModifiedModel, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/ha.py", line 319, in on_job_create
    instance=Instance.objects.me(),
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/managers.py", line 116, in me
    raise RuntimeError("No instance found with the current cluster host id")
RuntimeError: No instance found with the current cluster host id
2019-03-11 22:18:43,644 ERROR    django.request Internal Server Error: /api/v2/job_templates/7/launch/
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/wsgi.py", line 72, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/api/generics.py", line 334, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/api/views/__init__.py", line 2367, in post
    new_job = obj.create_unified_job(**serializer.validated_data)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/jobs.py", line 348, in create_unified_job
    job = super(JobTemplate, self).create_unified_job(**kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 384, in create_unified_job
    unified_job.save()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 839, in save
    result = super(UnifiedJob, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/polymorphic/models.py", line 83, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/base.py", line 198, in save
    super(PasswordFieldsModel, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/base.py", line 316, in save
    super(PrimordialModel, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/base.py", line 164, in save
    super(CreatedModifiedModel, self).save(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/models/ha.py", line 319, in on_job_create
    instance=Instance.objects.me(),
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/managers.py", line 116, in me
    raise RuntimeError("No instance found with the current cluster host id")
RuntimeError: No instance found with the current cluster host id
[pid: 9337|app: 0|req: 4/13] 192.168.153.1 () {50 vars in 2484 bytes} [Mon Mar 11 22:18:43 2019] POST /api/v2/job_templates/7/launch/ => generated 41 bytes in 342 msecs (HTTP/1.1 500) 6 headers in 208 bytes (1 switches on core 0)

**Comment by murali741** [comment]
Hi Martin,

I did fresh installation on another centos machine and it is working fine now. No issues


Thanks
Murali Medi

**Comment by MrMEEE** [comment]
Looks like you were missing some dependencies.. good that you got it to work :)
